### ISSUE TITLE
[FEATURE] Add option to ignore lint errors in the html

### ISSUE THREAD

**Issue by christopherpickering** [Riverside-Healthcare/djLint#113]
for example, maybe I need an inline style:

```html
<div style="width:{{ x * 3}}px"></div>
```

can I ignore the H021 code with something like this?
```html
{% djlint:ignore=H021 %}
<div style="width:{{ x * 3}}px"></div>
```

**Comment by jayvdb** [comment]
Would `{% djlint:ignore=H021 %}` be followed with another bit of syntax to reset the ignore list - i.e. is this issue about ignoring specific codes for a small line range, or just the next line.  ESLint has a 'eslint-disable-next-line' which auto-resets after a "line".

**Comment by carlotm** [comment]
Thank you for this amazing project, I was looking for something like this for years :)
I am lurking on this, as it is biting me.


What about this syntax:

```
{% djlint ignore=H021 ignore=H006 ... %}
   ...
{% enddjlint %}
```

TBH I am not sure if templatetags can be variadic though.

Again, kudos for this project!

**Comment by christopherpickering** [comment]
Thanks! I think I will expand the current syntax for ignoring.

So to ignore just H025:

```html
{# djlint:off H025,H026 #}
<p>
{# djlint:on #}

<!-- djlint:off H025-->
<p>
<!-- djlint:on -->

{% comment %} djlint:off H025 {% endcomment %}
<p>
{% comment %} djlint:on {% endcomment %}

{{!-- djlint:off H025 --}}
<p>
{{!-- djlint:on --}}

{{ /* djlint:off H025 */ }}
<p>
{{ /* djlint:on */ }}
```

**Comment by sr-verde** [comment]
Wow, that was pretty fast now. Thank you!

**Comment by christopherpickering** [comment]
hey @marty0678 do you mind opening a new issue? Thanks!
