### ISSUE TITLE
Invalid formatting of some user defined 'enclosing' tags 

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [Riverside-Healthcare/djLint#12]
test.html

```html
{% load my_tags %}
{% block main %}
    {% fragmentation %}
        {% toc %}
            {% include "cms/includes/streamfield.html" with blocks=self.body %}
        {% endtoc %}
    {% endfragmentation %}
{% endblock main %}
```

```djlint test.html --reformat```

test.html

```html
{% load my_tags %}
{% block main %}
    {% fragmentation %}
    {% toc %}
    {% include "cms/includes/streamfield.html" with blocks=self.body %}
{% endtoc %}
{% endfragmentation %}
{% endblock main %}
```

I would expect test.html format to remain unchanged. It looks like djlint doesn't recognise the custom tags (fragmentation, endfragmentation, toc, endtoc) and treats 'endtoc' as closing the 'block main'. 

Discussion

While it is true that it is impossible without looking at the code definition of the user-defined tags that toc and endtoc are paired, djlint might rely on the widespread naming convention in django where the name of the closing tag starts with 'end'. Obviously it's a heuristic that would require pre-processing and if {% endtoc %} was accidentally missing from the template, there's no way djlint would be able to tell. On the other hand it could be a very handy feature for larger projects where user-defined tags or third-party tags are more common.

Maybe as an alternative these pair of tags (toc - endtoc) could be declared somewhere in a config file to let djlint lint and format them as expected.

What do you think about the issue and the suggestions?

**Comment by christopherpickering** [comment]
Thanks, thats a good point! Probably both of your suggestions are good ways to go - check for `{% endtoc %}` using toc as a tag name, and also allow user config to list custom tag names.
