### ISSUE TITLE
[FEATURE] Disable reformatter for an entire file

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#122]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

In order to ignore an entire file, it must start with one of the `djlint:off` and an `djlint:on` at the end of the file.

It is a bit silly to re-enable djlint at the end of the file.

Also I might want the file to be linted, but not reformatted.

**Comment by christopherpickering** [comment]
Using the ``exclude`` is intended for this use case. I will close for now, comment back if I'm misunderstanding!
