### ISSUE TITLE
[FEATURE] Consecutive spaces in template tag invocation

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#123]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

The following (two spaces after 'static') doesnt cause a lint error, and isnt fixed by the reformatter.

```html
<link href="{% static  'foo/bar.min.css' %}"
      rel="stylesheet">
```

**Comment by christopherpickering** [comment]
Thanks, for now I think I will just add this to the linter.
