### ISSUE TITLE
[Question] Is there any plan to Linter integration for Editor/IDE?

### ISSUE THREAD

**Issue by yaegassy** [Riverside-Healthcare/djLint#13]
Thanks for this tool. Do you have any plans for djlint as a linter to run from the Editor or IDE?

Also, in that case, it might be good to have stdin support as well.

**Example:**

```
cat polls/templates/index.html | djlint --check  -
```

**Comment by christopherpickering** [comment]
Thanks, I haven't used ``--check`` in an ide yet, but do plan to add ``--reformat`` to the [sublime text linter](https://github.com/christopherpickering/Sublimelinter-contrib-djlint) as a keyboard shortcut to reformat an open file.

Sublime uses temp files so there was no need for stdin, but its something to consider. What editor would you use it in?

**Comment by yaegassy** [comment]
Thanks reply. I'm using Vim.

If stdin is not supported, you can of course create a tempfile and use that. Is it possible that djlint is more of a formatter tool than a pure linter?

If stdin is supported by linter, it is possible to run lint in some real time without saving the file.

For example, a tool similar to djlint is curlylint. 

- <https://github.com/thibaudcolas/curlylint>

If you want to support stdin in linter, the implementation of curlylint may be helpful.

**Comment by christopherpickering** [comment]
Thanks, I'll check it out! Feel free to pr if you have free time :) 

djlint does both linting and formatting, but the codebases are completely separate. The linter is more to check for potential html problems, not formatting problems.

**Comment by yaegassy** [comment]
This is an aside.

I'm working on a Vim/Neovim (use `coc.nvim` plugin) extension for some linter and formatter.

- <https://github.com/yaegassy/coc-curlylint>
- <https://github.com/yaegassy/coc-htmldjango/pull/2>

In the case of django html, the formatter uses `djhtml`.

It would be nice if djlint's linter feature could also be easier to integrate. 🙇

**Comment by christopherpickering** [comment]
I'll create a new release on pypi shortly with this feature. 
You can use it w/

```sh
echo "<div></div>" | djlint -
```

Thanks for the idea!

**Comment by yaegassy** [comment]
@christopherpickering 

Does this not require the `--check` option?

**none**:

```
djLint$ poetry shell
Spawning shell within /Users/yaegassy/_Dev/source/djLint/.venv
. /Users/yaegassy/_Dev/source/djLint/.venv/bin/activate
djLint$ . /Users/yaegassy/_Dev/source/djLint/.venv/bin/activate
(.venv) djLint$ echo "  <div></div>" | djlint -

Linting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00


Linted 1 file, found 0 errors.
```

**add --check**:

```
djLint$ poetry shell
Spawning shell within /Users/yaegassy/_Dev/source/djLint/.venv
. /Users/yaegassy/_Dev/source/djLint/.venv/bin/activate
djLint$ . /Users/yaegassy/_Dev/source/djLint/.venv/bin/activate
(.venv) djLint$ echo "  <div></div>" | djlint --check -

Checking 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00


/var/folders/v_/b5wzz2q96q5cqgdtl3fq066r0000gn/T/tmps6shebjj
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -1 +1 @@

-  <div></div>
+<div></div>

1 file would be updated.
```

**Comment by christopherpickering** [comment]
Both are correct.

- no args > code will be linted using the linter rules. The linter does not check formatting.
- ``--check`` > does the code need to be reformatted - shows what will happen if you run ``--reformat``?
- ``--reformat`` > reformat the code

for your check
```html
    <div></div>
```
will be reformatted to
```html
<div></div>
```
 note, no leading space.

**Comment by christopherpickering** [comment]
I'd recommend using no args for an IDE, and make a keyboard shortcut to run the ``--reformat`` option. the ``--check`` is only for when you are feeling insecure about changes that might be coming ;)

**Comment by yaegassy** [comment]
I'm sorry to bring up a different topic in this issue, but is it possible to output the row numbers and columns with errors?

This is an example of `curlylint`.

```
(.venv) curlylintcheck$ echo "  <div>{{</div>" | curlylint --quiet --format json -
[{"file_path": "-", "line": 1, "column": 0, "message": "Parse error: expected one of '-', 'any character', '}}' at 1:0", "code": "parse_error"}]
```

**Comment by christopherpickering** [comment]
![Uploading image.png…]()

**Comment by yaegassy** [comment]
Oh, I see. I understand. Thanks!!!

**Comment by christopherpickering** [comment]
np, check out this regex for parsing: https://github.com/christopherpickering/Sublimelinter-contrib-djlint/blob/master/linter.py

**Comment by yaegassy** [comment]
I'll try a regex.  Thank you so much!!!
(If there is also a "json" output option, parsing is reliable and easy, but...)

**Comment by christopherpickering** [comment]
https://github.com/Riverside-Healthcare/djLint/issues/18

**Comment by yaegassy** [comment]
Wow. Thank you very much for considering responding. 🙇 

Perhaps now the various editors/IDEs will be able to work with djLint smoothly!

**Comment by yaegassy** [comment]
@christopherpickering I supported `djlint` integration in my "Vim" extension. Thank you once again!

### DEMO

https://user-images.githubusercontent.com/188642/134281218-7a0c6862-dddd-4db5-9bc1-7879d69e9e9c.mp4

**Comment by christopherpickering** [comment]
Pretty nice, thanks for sharing! I wonder if we should add an "integrations" section to the docs... Is there a link to instructions on how to use this that I can add?

**Comment by yaegassy** [comment]
In the integrations section, my plugin (extension) is not a djLint-specific plugin, so it is not necessary. 🙇
