### ISSUE TITLE
[FEATURE] Add angular profile

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#138]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Angular html is fairly regular html, with a bit of template logic, except

1. H012 shouldn't apply for any html attribute beginning with `*` (see `*ngFor` below), and probably not any html attribute name exclosed in `[..]` (see `[class]` below), 
2. H026 is getting triggered by `<div [class]="isFullScreen ? 'full-width' : ''" ..>..`
3. and T028 is getting triggered by

```html

    <ng-container matColumnDef="{{ column.name }}" *ngFor="let column of tableColumns; let i = index">

```

And obviously D018/J018 shouldnt apply.

I could do a PR for this one if the concept is ok.

**Comment by christopherpickering** [comment]
I agree w/ your recommendation for H012 and H026.
