### ISSUE TITLE
[BUG] [Formatter] Reformatting blocktrans leads to changed content

### ISSUE THREAD

**Issue by dyve** [Riverside-Healthcare/djLint#144]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: macOS 12.0.1
 - Python Version: 3.8.12
 - djLint Version: 0.6.2

## Issue

Reformatting `blocktrans` makes meaningful changes the content of the tag, leading to translation issues.

Note that `blocktrans` is an alias of `blocktranslate`. See https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#blocktranslate-template-tag

## How To Reproduce

Create this template file `temp.html`:
```
<p>{% blocktrans %}Some trimmed text.{% endblocktrans %}</p>

<p>{% blocktrans trimmed %}Some trimmed text.{% endblocktrans %}</p>
```

Run Django `makemessages` and check the relevant section of the generated `django.po` file. There is 1 translatable string:
```
#: temp.html:1 temp.html:3
msgid "Some trimmed text."
msgstr ""
```

Now reformat with `djlint --reformat temp.html`, and you get this result:

```
<p>
    {% blocktrans %}
        Some trimmed text.
    {% endblocktrans %}
</p>
<p>
    {% blocktrans trimmed %}
        Some trimmed text.
    {% endblocktrans %}
</p>
```

Run Django `makemessages` and check the relevant section of the generated `django.po` file. There are now 2 different translatable strings:

```
#: temp.html:2
msgid ""
"\n"
"        Some trimmed text.\n"
"    "
msgstr ""

#: temp.html:7
msgid "Some trimmed text."
msgstr ""
```

Possible/probable solution is that the content of a `blocktrans` tag should not be reformatted. Even with `trimmed`, you may change translation tokens, since `trimmed` only ignores whitespace at the beginning and the end of the content.

## Configuration

```
# pyproject.toml
[tool.djlint]
# Reference: https://djlint.com/djlint/rules.html
profile = "django"
ignore = "H006,H008,H013,H014,H017,H019,H021,H023,T001,T002,T003"
blank_line_after_tag = "load,extends,include"
max_line_length = 120
```

**Comment by christopherpickering** [comment]
Thanks for pointing this out! djlint was setup for `blocktranslate` but from the docs looks like `blocktrans` will always be supported. I'll add it w/ `blocktranslate`.

The normal djlint behavior is to ignore blocks that do not have the "trimmed" tab.

**Comment by dyve** [comment]
Note that `trans` is alias for `translation`, also to be around forever. Might be relevant.

**Comment by dyve** [comment]
If it's possible to release 0.6.3 with this fix and maybe a fix for #146, I'd be much obliged. This is blocking the research of suitability for djlint as the default formatter in our code. I'll keep the bug reports coming in :-)

**Comment by christopherpickering** [comment]
Oh shucks, sorry I didn't realize I hadn't released this one yet! I'll release with a fix for 146 as well.

**Comment by dyve** [comment]
Thanks @christopherpickering. I'm just trying to show enthusiasm, don't feel compelled let alone bullied into releasing.

**Comment by christopherpickering** [comment]
😁 np, I don't like to leave hanging bugs 😁
