### ISSUE TITLE
[FEATURE] Extension for VS code

### ISSUE THREAD

**Issue by dyve** [Riverside-Healthcare/djLint#145]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Create an extension for VS Code that enables reformatting of Django templates.

**Comment by christopherpickering** [comment]
Thanks! Are you able to help with this one? I never work with vs-code.

There are a few external tools:
There is a tool for VIM https://awesomeopensource.com/project/yaegassy/coc-htmldjango?...=
And also sublimetext (for linting only) https://github.com/christopherpickering/Sublimelinter-contrib-djlint

And also pre-commit, which is in this repo.

I'm not sure how vs-code works - do you think that project should be in its own repo, or is small enough (like pre-commit) to be here?

**Comment by dyve** [comment]
Same here, I use VS Code as a user, but I have no experience writing extensions for it. I'm leaving this as a request for someone else.

A workaround would be to set `djlint`to run on save of certain HTML files. This is how I first learned about the project, see https://stackoverflow.com/a/68667543/117831

**Comment by dyve** [comment]
I'd agree with closing this issue as a wontfix, with the workaround documented above.
