### ISSUE TITLE
[BUG] [Formatter] Reformat can break links that contain `if` tag

### ISSUE THREAD

**Issue by dyve** [Riverside-Healthcare/djLint#152]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: macOS 12.0.1
 - Python Version 3.8.12
 - djLint Version 0.6.5

## How To Reproduce

Create this template (`temp.html`):

```
<a href="{{ url }}{% if redirect_field_value %}?next={{ redirect_field_value }}{% endif %}">this is a link with a long description</a>
```

Reformat it with `djlint --reformat temp.html` (see below for configuration).

```
<a href="{{ url }}
         {% if redirect_field_value %}
             ?next={{ redirect_field_value }}
         {% endif %}">
    this is a link with a long description
</a>

```

Note that the link is now broken if `redirect_field_value` contains a string :-(

## Configuration

```
[tool.djlint]
# Reference: https://djlint.com/djlint/rules.html
profile = "django"
ignore = "H006,H008,H013,H014,H017,H019,H021,H023,T001,T002,T003"
blank_line_after_tag = "load,extends,endblock,has_perm"
max_line_length = 120
```

**Comment by christopherpickering** [comment]
thanks, thats in django? Do you know if there is an equiv of the `{%- if -%}` from jinja?

**Comment by christopherpickering** [comment]
If there is no equivalent of https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control in Django, we should probably disable formatting template syntax inside of attributes for the Django profile.. It messes up `<input value="{% if %}">` and also form actions.

**Comment by dyve** [comment]
Alas, Django has no equivalent for `{%- -%}`

**Comment by christopherpickering** [comment]
I created my first django ticket... not sure if it will fly 😁 

In djlint we can add an option to not format template syntax in attribute values. I suppose the default should be "not format".

**Comment by christopherpickering** [comment]
It didn't fly 😁 https://code.djangoproject.com/ticket/33329#ticket

I guess if you wrap it in `{%spaceless%} {% endspaceless%}` it will work. I'll update the docs with that.

I'm adding a config option that will enable the attribute formatting... the default will be to disable it.

**Comment by dyve** [comment]
No, the `{% spaceless %}` tag only strips spaces between HTML tags, not inside attributes.
