### ISSUE TITLE
[FEATURE] Generic configuration file

### ISSUE THREAD

**Issue by tissieres** [Riverside-Healthcare/djLint#170]
- [X] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [X] I've read the [docs](https://djlint.com)

## Feature Request
Hi, I'm looking for a way to specify some formatting configuration like `blank_line_after_tag="load,extends,include"` "system-wide". Would it be possible to add a cli option to specify the path for a generic configuration file instead of defining the configuration for each project? 

Thanks in advance

**Comment by christopherpickering** [comment]
Thanks for the suggestion, I can take a look into that.
