### ISSUE TITLE
[BUG] [Formatter] Multi-line `{% comment %}` has unstable ident 

### ISSUE THREAD

**Issue by vchga** [Riverside-Healthcare/djLint#173]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: ubuntu 20.04
 - Python Version: 3.9.5
 - djLint Version: 0.7.2
 - template language: django

## Issue
When using block comment for more than 2 lines, ident is added to the block content with every reformat. I'd like `{% comment %}` to not change ident of inner content at all (disable formatting, like djlint:off), because comments in general may contain invalid code (e.g. variant of opening html tag and such).

## How To Reproduce

This is simple example, where I provide formatted code according to my liking, but reformat is making unwanted indent and is not being idempotent (it changes the file with every re-run - see bellow).

```html
<html>
    <head>
        <script src="file1.js"></script>
        {% comment %}
        <script src="file2.js"></script>
        <script src="file3.js"></script>
        <script src="file4.js"></script>
        {% endcomment %}
        <script src="file5.js"></script>
    </head>
    <body>
    </body>
</html>
```

After running reformat for the first time:
- script inside comment is indented (which I prefer not to)
- endcomment is wrongly underindented
- rest of the file after endcomment is off

```html
<html>
    <head>
        <script src="file1.js"></script>
        {% comment %}
                <script src="file2.js"></script>
                <script src="file3.js"></script>
                <script src="file4.js"></script>
    {% endcomment %}
    <script src="file5.js"></script>
</head>
<body>
</body>
</html>
```

Running reformat the second time:
- more unwanted indent is added to inner content of comment

```html
<html>
    <head>
        <script src="file1.js"></script>
        {% comment %}
                        <script src="file2.js"></script>
                        <script src="file3.js"></script>
                        <script src="file4.js"></script>
    {% endcomment %}
    <script src="file5.js"></script>
</head>
<body>
</body>
</html>
```

This has similar symptoms as djlint:on/off issue in https://github.com/Riverside-Healthcare/djLint/issues/166#issuecomment-1007409478.

Just for fun I've put djlint:on/off around comment/endcomment and it has no effect :( I'll log it as separate issue.

**Comment by christopherpickering** [comment]
Thanks! The problem is the nested ignore blocks :/ I'll see what I can do!
