### ISSUE TITLE
Add option / configuration to ignore paths

### ISSUE THREAD

**Issue by matthiask** [Riverside-Healthcare/djLint#22]
The `ignored_paths` setting cannot be extended currently:
https://github.com/Riverside-Healthcare/djLint/blob/678e50088cdfa29f0f525b035f6207327d0c7e04/src/djlint/settings.py#L64-L83

I'd want to exclude e.g. `templates/registration/password_reset_email.html` from reformatting because the template contains text for an email (despite the incorrect `.txt` extension) but currently there's no way to do that (if I understand the code correctly).

By the way, flake8 uses `ignore` for error codes and `exclude` for paths, and `extend-exclude` to add additional patterns to exclude. https://flake8.pycqa.org/en/3.9.2/user/options.html?highlight=exclude#cmdoption-flake8-exclude I think that's an excellent naming. I'm willing to do the work if you agree but didn't want to drop a big pull request without checking first.

**Comment by christopherpickering** [comment]
Thanks, yes, please send over a pr, I'm happy with what flake8 does as well.
