### ISSUE TITLE
[BUG] [Formatter] Issues supporting custom elements with `custom_html`

### ISSUE THREAD

**Issue by danstewart** [Riverside-Healthcare/djLint#236]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Fedora 36
 - Python Version: Python 3.10.4
 - djLint Version: 1.0.0
 - template language: Jinja2

## Issue

We use custom HTML elements so have added a `custom_html` regex to handle them:
```
custom_html = '\w+-\w+-\w+-\w+,\w+-\w+-\w+,\w+-\w+'
```

This has mostly worked but I've run into an issue when I have a custom element tag with 4 parts, eg: `<some-long-custom-element>`.
Adding a `djlint:off` comment also doesn't stop the formatter.

BEFORE
```jinja
<some-long-custom-element></some-long-custom-element>

{# djlint:off #}
<some-long-custom-element></some-long-custom-element>
{# djlint:on #}

{# djlint:off #}<some-long-custom-element></some-long-custom-element>{# djlint:on #}
```

AFTER
```jinja
<some-long-custom -element>
</some-long-custom-element>
{# djlint:off #}
<some-long-custom -element></some-long-custom-element>
{# djlint:on #}
{# djlint:off #}<some-long-custom -element></some-long-custom-element>{# djlint:on #}
```

---

I've thrown up an example in this repository:
https://github.com/danstewart/djlint-issue

I've tried having a look at where it's going wrong but I'm struggling to figure it out.
It looks like `custom_html` regex is used in a few places and this regex just breaks things.

Is there a better way to support arbitrary custom HTML elements?

**Comment by christopherpickering** [comment]
Thanks! It looks like the issue is coming from the attribute compress. I'll put a fix out for this case shortly!

**Comment by danstewart** [comment]
Wow, that was fast!
That works as expected, thanks a lot :slightly_smiling_face:
