### ISSUE TITLE
[BUG] [Formatter]This breaks when formatting a django template with Japanese characters in UTF-8.

### ISSUE THREAD

**Issue by Taikono-Himazin** [Riverside-Healthcare/djLint#243]
Running the following command produces corrupted output.

```
echo "{% if field.field.required %}\n<span span class=\"badge badge-danger\">{{ required | default:'必須' }}</span>\n{% endif %}" | djlint - --reformatmat
```

output
```
{% if field.field.required %}\n<span span class=\ badge badge-danger\>{{ required | default:'??' }}</span>\n{% endif %}
```

Do you only deal with ascii characters in djlint?
I noticed that when using djlint-vscode with vscode, I get corrupted output.
When I tried the above command, djlint gave corrupted output.

Below is my environment.

- OS -Windows 10 Japanese
- Python 3.9.10
- djLint version -1.0.2

**Comment by monosans** [comment]
According to my observations, the issue is only on Windows.

**Comment by Taikono-Himazin** [comment]
If you turn on "Beta: Use Unicode UTF-8 with worldwide language support" in the system locale setting of windows, you can do it without any problem.
It seems to be a problem with windows settings. Thank you.

**Comment by christopherpickering** [comment]
Thanks @Taikono-Himazin  and @monosans!

**Comment by christopherpickering** [comment]
Reopening to fix this:

![](https://user-images.githubusercontent.com/17788706/169035670-21017104-9148-4a2e-ab31-223e20c87ef8.png)

**Comment by Taikono-Himazin** [comment]
After applying this update, it worked fine even if I restored the Windows settings!
thank you!

**Comment by christopherpickering** [comment]
Nice! Thank you!
