### ISSUE TITLE
[FEATURE]Is there an option not to format the attribute?

### ISSUE THREAD

**Issue by Taikono-Himazin** [Riverside-Healthcare/djLint#251]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

I don't want to break the attributes of html tags into multiple lines. It has such a code convention.
But this makes the following code 
```
<a href="#" rel="hover" class="dt-btn dt-btn-sidebar" data-action="toggle" data-side="left">
```
look like this:
```
<a href="#"
   rel="hover"
   class="dt-btn dt-btn-sidebar"
   data-action="toggle"
   data-side="left">
```
How can I output the attributes as one line?
Should I change any options?
I set max_line_length and max_attribute_length to 999, but it didn't change.

**Comment by christopherpickering** [comment]
Hi,
Thanks for the question, if I add
```
[tool.djlint]
max_attribute_length=99999
```
to my `pyproject.toml`, the output is not changed:

![image](https://user-images.githubusercontent.com/17788706/170493006-4367a730-14d1-4780-9cb3-5ae45d5b09ec.png)


![image](https://user-images.githubusercontent.com/17788706/170492979-8b60f3bf-28e7-49fc-a7e1-a32ce67fd8e1.png)

Does that work for you?

**Comment by Taikono-Himazin** [comment]
thank you!
I tried it again and it was done.
It seems that the name of the configuration file was wrong.
I'm sorry.
