### ISSUE TITLE
[FEATURE] Prevent text identation

### ISSUE THREAD

**Issue by rickdonato** [Riverside-Healthcare/djLint#260]
## Feature Request
The feature is to provide an option to prevent text being completely aligned when formatted. 
For example if I have this text:
```
interface Ethernet1/2
  description // Connected to leaf-2
  no switchport
  ip address 10.1.2.1/30
  ip router ospf 1 area 0.0.0.0
  no shutdown

interface Ethernet1/3
  description // Connected to leaf-3
  no switchport
  ip address 10.1.3.1/30
  ip router ospf 1 area 0.0.0.0
  no shutdown
```
And I run the following I get all text aligned. 
```
❯ djlint 1234  --profile=jinja --check

Checking 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:01


home/rick/1234
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -1,13 +1,12 @@

 interface Ethernet1/2
-  description // Connected to leaf-2
-  no switchport
-  ip address 10.1.2.1/30
-  ip router ospf 1 area 0.0.0.0
-  no shutdown
-
+description // Connected to leaf-2
+no switchport
+ip address 10.1.2.1/30
+ip router ospf 1 area 0.0.0.0
+no shutdown
 interface Ethernet1/3
-  description // Connected to leaf-3
-  no switchport
-  ip address 10.1.3.1/30
-  ip router ospf 1 area 0.0.0.0
-  no shutdown
+description // Connected to leaf-3
+no switchport
+ip address 10.1.3.1/30
+ip router ospf 1 area 0.0.0.0
+no shutdown

1 file would be updated.
```
Ideally it would be good to have the option where the text is not aligned.

Thanks,

**Comment by christopherpickering** [comment]
Hey @rickdonato I pushed an attempt at this onto the dev branch. Your example works, but maybe you have others you can test out locally.

You can install it w/:
```
pip uninstall djlint
pip install git+https://github.com/Riverside-Healthcare/djLint.git@dev 
```

And run by adding `--preserve-leading-space` option, or `preserve-leading-space=true` in your pyproject file.

Let me know how it goes.

**Comment by rickdonato** [comment]
Hey man. Thanks for the quick response/update : ) 
I did some testing. The preserve leading space seems to work as expected. 
But it seems have broken the formatting of J2 for example:
```
❯ cat config.txt
     {% if   abc == 101 %}
 interface Ethernet1/2
   description // Connected to leaf-2
   no switchport
   ip address 10.1.2.1/30
   ip router ospf 1 area 0.0.0.0
   no shutdown
{% endif %}


{% if abc == 102 %}
 interface Ethernet1/2
   description // Connected to leaf-2
   no switchport
   ip address 10.1.2.1/30
   ip router ospf 1 area 0.0.0.0
   no shutdown
  {% endif %}

{% if abc == 103 %}
 interface Ethernet1/2
   description // Connected to leaf-2
   no switchport
   ip address 10.1.2.1/30
   ip router ospf 1 area 0.0.0.0
   no shutdown
            {% endif %}
```
If I now reformat this I get:
```
$ djlint config.txt --indent=1 --profile=jinja --reformat --preserve-leading-space
1 file was updated.
...
$ cat 1234
{% if   abc == 101 %}
  interface Ethernet1/2
    description // Connected to leaf-2
    no switchport
    ip address 10.1.2.1/30
    ip router ospf 1 area 0.0.0.0
    no shutdown
{% endif %}


{% if abc == 102 %}
  interface Ethernet1/2
    description // Connected to leaf-2
    no switchport
    ip address 10.1.2.1/30
    ip router ospf 1 area 0.0.0.0
    no shutdown
   {% endif %}

 {% if abc == 103 %}
   interface Ethernet1/2
     description // Connected to leaf-2
     no switchport
     ip address 10.1.2.1/30
     ip router ospf 1 area 0.0.0.0
     no shutdown
              {% endif %}
```
So it seems like it did the indent but not the reformatting of the J2. I tested this same J2 in the main release (non dev) and the formatting works. 

Thanks again dude...

**Comment by rickdonato** [comment]
The other thing I was thinking is whether there would be an option to not indent at all. just to leave the text inside the J2 along.  Happy to raise later, in another issue if required. Just a thought, and don't want to muddy any water with this issue : ) Thanks again.

**Comment by christopherpickering** [comment]
Thanks! I tried to take care of both of those things. Can you test again? Do you have a public repo with templates I can take a look at?

Let me know how it goes.

**Comment by rickdonato** [comment]
Great thanks. Initial tests of the J2 formatting look good. I will test more and confirm. As for J2 templates, I don't have any to hand, I've just quickly built some dummy ones for testing. 

When you mentioned covering both cases did you also mean the ability not to indent at all?

Thanks again,

**Comment by christopherpickering** [comment]
Yep, so when I format the text you supplied above, I get this: (notice no indent on any text, only jinja tags, or html if they were there). So if you were using a for loop to get a list of addresses it should be cool as well.

![image](https://user-images.githubusercontent.com/17788706/174083070-36b7bbde-d9da-4f48-b2ab-cb080b47f033.png)

**Comment by rickdonato** [comment]
Ah ok cool. Yep I see now. I thought there was another option. Yep looks great. I do wonder though wether folks may get confused as `--preserve-leading-space` is basically also disabling the indent option. i.e it is perseving leading space and over disabling indent. I may be over thinking things. We could maybe change to disable-indent or give folks the option to set both parameters. Just a thought. As it stands it works great at the mo.

Small note `{% if   abc == 101 %}` was not formatted. 

Thanks again for the help. Also when will the next release be out with this new feature in.

**Comment by christopherpickering** [comment]
Well, if you have a more complex template you will see that anything non-text is still indented. The option is just trying to keep any text as-is. Some will be changed by default in an html doc, but for cases like yours hopefully it works well. 

I will add a test for this and do a release soon.

**Comment by rickdonato** [comment]
Understood. Thanks again for all your help.
