### ISSUE TITLE
[BUG] [Formatter] Whitespaces in Jinja Code

### ISSUE THREAD

**Issue by sr-verde** [Riverside-Healthcare/djLint#287]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Linux 5.18.9-arch1-1
 - Python Version: 3.10.5
 - djLint Version: 1.6.0
 - template language: Jinja2

## Issue
Jinja code with list and tuples with whitespaces are not reformatted consistently.
I know, one can interpret that as a bug or as a feature request.

## How To Reproduce
Try to reformat this file:

```
{% set table_keys = [ ( "date_started", "Start date"), ( "name", "Name" )] %}
```

I would expect no whitespaces within the tuple definition:

```
{% set table_keys = [("date_started", "Start date"), ("name", "Name")] %}
```

But djlint does not reformat this file in any way.

## Notes

Thank you and all contributors for this awesome project!

**Comment by christopherpickering** [comment]
Thanks! Currently the contents of `{% tags %}` are not changed. I'm going to change this to a feature request - once we switch to the template parser (instead of regex and line splitting) I think it will be easily doable.

**Comment by christopherpickering** [comment]
#168

**Comment by sr-verde** [comment]
:tada: :+1:
