### ISSUE TITLE
[FEATURE] indent cli option

### ISSUE THREAD

**Issue by robphoenix** [Riverside-Healthcare/djLint#29]
- [ x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [ x] I've read the [docs](https://djlint.com)

## Feature Request
 
I've come from here https://github.com/yaegassy/coc-htmldjango/issues/8

Is it possible to set the indent configuration from the CLI?
Thanks

**Comment by christopherpickering** [comment]
Thanks, I'll put out a new release in a few minutes. djlint==0.4.3

**Comment by yaegassy** [comment]
@christopherpickering Hi, Can't we make it a "number" instead of a string of whitespaces? 

- e.g. `--indent=2`
- e.g. `--indent 2`

**Comment by christopherpickering** [comment]
@yaegassy yes, I suppose that is more consistent with other formatters.

**Comment by robphoenix** [comment]
Amazing, thanks @christopherpickering 🙏🏻 🚀
