### ISSUE TITLE
[BUG] [Formatter] Extra blank lines inserted after blank_line_after_tag tags with preserve_blank_lines

### ISSUE THREAD

**Issue by aarongoldenthal** [Riverside-Healthcare/djLint#297]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 10 21H2
 - Python Version (``python --version``): 3.10.3
 - djLint Version (``djlint --version``): 1.7.1
 - template language: nunjucks

## Issue

Using nunjucks templates with `preserve_blank_lines: true`, any tag listed in `blank_line_after_tag` has a new blank line inserted after it on every `reformat`.

The expected behavior in this case is that a blank line is inserted after the identified tags in `blank_line_after_tag` only if there is not already a blank line.

## How To Reproduce

With config:

```json
{
  "blank_line_after_tag": "extends",
  "preserve_blank_lines": true
}
```

and nunjucks file:

```njk
{% extends "layouts/base.njk" %}

<!-- other content -->
```

run `djlint --reformat **/*.njk` muliple times, and each time it adds a new blank after the `extends` tag.

This looks like it's related to https://github.com/Riverside-Healthcare/djLint/issues/79.

**Comment by christopherpickering** [comment]
Thanks @aarongoldenthal !
