### ISSUE TITLE
[BUG] [Linter] Unclosed string found in template syntax

### ISSUE THREAD

**Issue by jace** [Riverside-Healthcare/djLint#301]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: macOS 12.4
 - Python Version: 3.9.13
 - djLint Version: 1.7.2
 - template language: jinja

## Issue

djLint is insisting the following two lines have unclosed strings in template syntax. I do not see any unclosed strings. The mixed use of single and double quotes is also because djLint confuses some of these to be HTML attributes and insists on double quotes.

## How To Reproduce

```jinja2
{% macro rendersubmit(buttons=[], css_class="", tabindex='', cancel_url='', style="horiz", csrf_error=false) -%}
…
{% endmacro %}

{%- macro renderform(form, formid, submit, ref_id="form", message='', action=None, cancel_url='', multipart=false, style="", autosave=false, draft_revision=none) %}
…
{% endmacro %}
```

```
T027 1:0 Unclosed string found in template syntax. {% macro rendersubmi
T027 5:0 Unclosed string found in template syntax. {%- macro renderform
```

**Comment by christopherpickering** [comment]
Hey @jace thanks. I can't reproduce it by copying what you have. Can you send a more complete file? There must be some leading text causing the issue.

![image](https://user-images.githubusercontent.com/17788706/181014649-f0cd9620-99be-458d-9970-6d5463a28604.png)

**Comment by jace** [comment]
The full file: https://github.com/hasgeek/funnel/blob/ef266faadd4c48ee6417c961651ec5cd391573e6/funnel/templates/forms.html.jinja2

**Comment by christopherpickering** [comment]
My bad, I missed you were running w/ `--profile=jinja`. I get the message now 👍🏽

**Comment by christopherpickering** [comment]
It does seem to be the mixed quotes causing a runnaway regex :) I will split up the regex and put a fix out soon. Thanks!
