### ISSUE TITLE
[BUG] [Linter]

### ISSUE THREAD

**Issue by SKHDev195** [Riverside-Healthcare/djLint#305]
## System Info
 - OS: Windows 10
 - Python Version: 3.7.9
 - djLint Version: 1.7.4
 - template language: HTML

## Issue
When opening and formatting any HTML template in VS Code with djLint installed and configured, the "Problems" tab shows all problems detected in the related temporary templates. 

## How To Reproduce
By opening any HTMl template in VS Code with djLint installed in the current virtual environment/attempting to save the template/pressing the 'Format document' keyboard shortcut. 
<img width="1079" alt="Screenshot 2022-07-28 125442" src="https://user-images.githubusercontent.com/106549059/181453148-769ccba7-9bb4-453e-8de1-8de249bbd2fc.png">

**Comment by holohup** [comment]
Got same issue on macos 12.4, vscode 1.69.2, python 3.7.13. The linter keeps generation hundreds of problems while the .html template file is open. Currently, I avoid those distracting messages by using the VSCode filter "Show active files only", but would be much happier to find out how to fix this error.

**Comment by Finegorko** [comment]
++

**Comment by christopherpickering** [comment]
Hi guys, thanks. I'm thinking this issue belongs in the vscode extension repo. https://github.com/monosans/djlint-vscode
