### ISSUE TITLE
[BUG] [Formatter]Formatter breaks <a> when there is whitespace between "=" and a long text 

### ISSUE THREAD

**Issue by andr3h3nriqu3s11** [Riverside-Healthcare/djLint#317]
## System Info
 - OS: MacOS 12.4
 - Python Version 3.10.4
 - djLint Version 1.7.4
 - template language: html

## Issue

When there is a space between the `href=` and a long url (because small urls don't seam to trigger the character limit which does not cause any reformatting, at least that is my theory) the formatter breaks the url apart into other attributes.

Notes:
- Works perfectly fine without any spaces(`href="..."`) or with a space between `href` and `=`(eg. `href ="..."`) 
- It's not limited to the `href` attribute. Tried out with a "class" attribute with a long group of classes and it also broke.
- When trying to do the same on `<img>` with the attribute `src` it worked fine.

## How To Reproduce

File:
```html
<a href = "http://test.test:3000/testtesttesttesttesttesttesttesttesttest">Test</a>
```

which is formatted to, after running `djlint <filename> --reformat`:

```html
<a href
   http
   test.test
   3000
   testtesttesttesttesttesttesttesttesttest>Test</a>
```

Expected:
```html
<a href="http://test.test:3000/testtesttesttesttesttesttesttesttesttest">Test</a>
```

Or:

```html
<a class = "test test test test test test test test test test test test test">Test</a>
```

resulted in:

```html
<a class
   test
   test
   test
   test
   test
   test
   test
   test
   test
   test
   test
   test
   test>Test</a>
```

**Comment by christopherpickering** [comment]
Thanks! I will put a fix to stop breaking the contents of the attribute, and will add a feature request to remove the extra whitespace around the "=", right now that is not handled.
