### ISSUE TITLE
[BUG] [Linter] Can't ignore H006

### ISSUE THREAD

**Issue by aleprovencio** [Riverside-Healthcare/djLint#333]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Archlinux
 - Python Version (``3.10.6``)
 - djLint Version (``1.9.4``)
 - template language: django

## Issue
I'm not able to ignore `H006` ('img tag should have height and width attributes.').

## How To Reproduce
On `pre-commit` config use `args: ["-i H006"]` or use one of the methods provided on [documentation](https://djlint.com/docs/ignoring-code/)

**Comment by christopherpickering** [comment]
Hi, Can you provide some of the code? I'm unable to reproduce with this example:

```html
{# djlint:off H006 #}
<img />
{# djlint:on #}
```

H006 is ignored in the output:
```bash
H013 2:0 Img tag should have an alt attribute. <img />

Linted 1 file, found 1 error.
```

Or w/ a `.pre-commit-config.yaml`:

```yaml
repos:
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.9.5
  hooks:
    - id: djlint-django
      args: [-i, H006]
```
and a simple html file:
```html
<img />
```

```bash
git add .
pre-commit run --all-files
```
Does not return H006:

```bash
index.html

H013 1:0 Img tag should have an alt attribute. <img />

Linted 1 file, found 1 error.
```

**Comment by aleprovencio** [comment]
Thanks for the reply.

I'm not able to get the same results on your very first example:

> Hi, Can you provide some of the code? I'm unable to reproduce with this example:
> 
> ```
> {# djlint:off H006 #}
> <img />
> {# djlint:on #}
> ```
> 
> H006 is ignored in the output:
> 
> ```shell
> H013 2:0 Img tag should have an alt attribute. <img />
> 
> Linted 1 file, found 1 error.
> ```

My test is generating a project with `cookiecutter-django`, installing djlint on the `venv` and edit a template there the same way as you did.

**Comment by christopherpickering** [comment]
Thanks, can you give me the exact steps you follow from scratch to reproduce it?
eg: clone ..., virtualenv venv... venv/bin/python -m pip install djlint ... ?

**Comment by aleprovencio** [comment]
Sure,

1. cookiecutter gh:cookiecutter/cookiecutter-django --no-input
2. cd my_awesome_project/
3. python -m venv .venv
4. source .venv/bin/activate.fish
5. pip install -r requirements/local.txt
6. pip install djlint
7. nvim my_awesome_project/templates/500.html
8. *make changes above*
9. djlint --profile=django my_awesome_project/templates/500.html

**Comment by christopherpickering** [comment]
@aleprovencio I've copied your steps and still cannot reproduce it - I swapped the fish command for the one working on Mac, and used Nano instead of nvim.

 Here's some pics w/ the long pip logs removed:

![image](https://user-images.githubusercontent.com/17788706/185980138-653b112b-b3b5-4e77-a7ba-1dfb45bcb368.png)

![image](https://user-images.githubusercontent.com/17788706/185980181-f7d1c130-1053-45c1-bf2f-213a2fa1d58a.png)


![image](https://user-images.githubusercontent.com/17788706/185980229-6136c653-e421-49f9-92a6-52a5fe6833ae.png)

![image](https://user-images.githubusercontent.com/17788706/185980369-a3a3e4e4-fa6e-47c9-9446-aa87d349c594.png)

![image](https://user-images.githubusercontent.com/17788706/185980271-14ba8290-7996-40c4-9d8b-c7af61780a85.png)

**Comment by christopherpickering** [comment]
Fyi, I'm finally able to reproduce on a windows machine. I'll dig into it more, I wonder if it in a way the regex is being handled.

**Comment by christopherpickering** [comment]
Upgrading from djlint-1.3.0 to 1.11.0 fixed the problem on windows. Can you test out a `pip install --upgrade djlint`?

**Comment by aleprovencio** [comment]
Just tested it out.

Although specifying lint error like this, is still not working:
```
{# djlint:off H006 #}
```

...this code already works as expected:
```
{# djlint:off #}
```

So I guess you're on track 😃

**Comment by christopherpickering** [comment]
Ok cool thanks! This is getting close.

Do you have djlint in the .venv still? 

In the env/lib(?)/site-packages/djlint/helpers.py, can you add two print statements for me, and then run again?

![image](https://user-images.githubusercontent.com/17788706/186184737-4571e2d5-af30-4abc-b738-2e5a0f3c3f8f.png)

```
print(rule)
print(list(set(re.split(r"\s|,", ignored_match.group(1).strip()))))
```

rule should be "H006"
and the list should be "H006, H016" probably.... but maybe something else will show up :)

Otherwise, when you have time you can go on the discord and we can do a screen share on there to debug.

**Comment by aleprovencio** [comment]
Hey!
On the `500.html` file, with this code:
```
{# djlint:off H006 #}
<img />
{# djlint:on #}
```

The additional printed text is:
```
T003
['H006']
H006
['H006']
H006
['H006']
H013
['H006']

```
Note that finding `T003` makes sense because this file comes with this by default.

However, does this output mean that `T003` producing a `H006` lint error?

**Comment by aleprovencio** [comment]
Following your suggestions of #344:

Applying the additional `print(rule_regex)` on `helpers.py`:
```
<!--\s*djlint\:off(.+?)-->.*?(?=<!--\s*djlint\:on\s*-->)
{\#\s*djlint\:\s*off(.+?)\#}.*?(?={\#\s*djlint\:\s*on\s*\#})
T003
['H006']
{%\s*comment\s*%\}\s*djlint\:off(.*?)\{%\s*endcomment\s*%\}.*?(?={%\s*comment\s*%\}\s
*djlint\:on\s*\{%\s*endcomment\s*%\})
{{!--\s*djlint\:off(.*?)--}}.*?(?={{!--\s*djlint\:on\s*--}})
{{-?\s*/\*\s*djlint\:off(.*?)\*/\s*-?}}.*?(?={{-?\s*/\*\s*djlint\:on\s*\*/\s*-?}})
<!--\s*djlint\:off(.+?)-->.*?(?=<!--\s*djlint\:on\s*-->)
{\#\s*djlint\:\s*off(.+?)\#}.*?(?={\#\s*djlint\:\s*on\s*\#})
H006
['H006']
{%\s*comment\s*%\}\s*djlint\:off(.*?)\{%\s*endcomment\s*%\}.*?(?={%\s*comment\s*%\}\s
*djlint\:on\s*\{%\s*endcomment\s*%\})
{{!--\s*djlint\:off(.*?)--}}.*?(?={{!--\s*djlint\:on\s*--}})
{{-?\s*/\*\s*djlint\:off(.*?)\*/\s*-?}}.*?(?={{-?\s*/\*\s*djlint\:on\s*\*/\s*-?}})
<!--\s*djlint\:off(.+?)-->.*?(?=<!--\s*djlint\:on\s*-->)
{\#\s*djlint\:\s*off(.+?)\#}.*?(?={\#\s*djlint\:\s*on\s*\#})
H006
['H006']
{%\s*comment\s*%\}\s*djlint\:off(.*?)\{%\s*endcomment\s*%\}.*?(?={%\s*comment\s*%\}\s
*djlint\:on\s*\{%\s*endcomment\s*%\})
{{!--\s*djlint\:off(.*?)--}}.*?(?={{!--\s*djlint\:on\s*--}})
{{-?\s*/\*\s*djlint\:off(.*?)\*/\s*-?}}.*?(?={{-?\s*/\*\s*djlint\:on\s*\*/\s*-?}})
<!--\s*djlint\:off(.+?)-->.*?(?=<!--\s*djlint\:on\s*-->)
{\#\s*djlint\:\s*off(.+?)\#}.*?(?={\#\s*djlint\:\s*on\s*\#})
H013
['H006']
{%\s*comment\s*%\}\s*djlint\:off(.*?)\{%\s*endcomment\s*%\}.*?(?={%\s*comment\s*%\}\s
*djlint\:on\s*\{%\s*endcomment\s*%\})
{{!--\s*djlint\:off(.*?)--}}.*?(?={{!--\s*djlint\:on\s*--}})
{{-?\s*/\*\s*djlint\:off(.*?)\*/\s*-?}}.*?(?={{-?\s*/\*\s*djlint\:on\s*\*/\s*-?}})
```

And `print(inside_ignored_rule(config, html, match,rule["name"]))` on `lint.py` (`helpers.py` print statements off):
```
False
False
False
False
```

**Comment by christopherpickering** [comment]
> However, does this output mean that T003 producing a H006 lint error?

It means that T003 was found, and H006 is what you were trying to ignore.

I think I have a fix on the way, thanks!

**Comment by christopherpickering** [comment]
No prob, thank you!
