### ISSUE TITLE
[BUG] [Formatter] Djlint got stuck on my template

### ISSUE THREAD

**Issue by PetrDlouhy** [Riverside-Healthcare/djLint#340]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: ubuntu Linux 5.15.0-39-generic # 42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Python Version: Python 3.10.4
 - djLint Version: djlint, version 1.11.0
 - template language: django html template

## Issue
Djlint got stuck when formating my template. All other templates are formated quickly, but this one takes forever (not finished after more than 10 minutes).

## How To Reproduce
Run `djlint --check plan_table.html  --profile=django` on attached template (I renamed it from html to txt in order to fit here).

[plan_table.txt](https://github.com/Riverside-Healthcare/djLint/files/9386495/plan_table.txt)

**Comment by PetrDlouhy** [comment]
I tried to make minimal example of file with the problems. I was able to reduce it to the attached file, where `djlint` runs for ~30 seconds (which is very long considering how simple the file is). When I delete some of the parameters of the first `<div>` it gets faster.
[plan_table.txt](https://github.com/Riverside-Healthcare/djLint/files/9386517/plan_table.txt)

**Comment by christopherpickering** [comment]
It looks like this is producing `Catastrophic backtracking has been detected and the execution of your expression has been halted. To find out more and what this is, please read the following article: [Runaway Regular Expressions](http://www.regular-expressions.info/catastrophic.html)` on `expand.py:should_i_move_template_tag` on the findall. I'll see if there is a way to fix it.

**Comment by PetrDlouhy** [comment]
@christopherpickering Thank you very much for your work, now it work nicely :+1:

**Comment by christopherpickering** [comment]
Cool, thank you!
