### ISSUE TITLE
bug(H014): error if 2 empty lines

### ISSUE THREAD

**Issue by Kristinita** [Riverside-Healthcare/djLint#341]
### 1. Summary

[**H014 rule**](https://www.djlint.com/docs/linter#rules) of djLint linter:

```text
H014	More than 2 blank lines.
```

But I get H014 error if I have 2 blank lines in my template, not **more** than 2 blank lines.

#### 2.1. File to check

+ `KiraDJLint__2-blank-lines--H014.html`:

	```text
	Kira


	Goddess!

	```

#### 2.2. Desired behavior

No errors

#### 2.3. Current behavior

```text
D:\SashaDebugging\KiraDJLintDebuging>djlint --profile=jinja --lint KiraDJLint__2-blank-lines--H014.html

Linting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00


SashaDebugging\KiraDJLintDebuging\KiraDJLint__2-blank-lines--H014.html
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── H014 1:0 More than 2 blank lines. Kira

Linted 1 file, found 1 error.
```

### 3. Environment

1. Microsoft Windows [Version 10.0.19041.1415]
1. Python 3.10.6
1. djlint, version 1.11.0
1. Template language — Jinja

### 4. Checkbox

1. [x] I’m on the [**latest version**](https://pypi.org/project/djlint/) of djLint
1. [x] I’ve searched the [**issues**](https://github.com/Riverside-Healthcare/djLint/issues)
1. [x] I’ve read the [**docs**](https://djlint.com)

Thanks.

**Comment by christopherpickering** [comment]
Thanks, the wording on that rule is not clear, I'll update it.

**Comment by Kristinita** [comment]
**Status: I’m not sure about the need for a rule** :confused:

I’m not sure, that disallowing 2 empty lines is a good practice. 3 empty lines — yes, probably bad, but not 2.

For all file types (except Markdown, which uses a heading structure), I use 2 empty lines to separate large, related blocks of code, making the file more readable. Python, for example, [**officially prescribes**](https://peps.python.org/pep-0008/#blank-lines) “surround top-level function and class definitions with two blank lines”.

It would be nice to have a detailed explanation of this rule and some of the other rules, see **#345**.

Thanks.

**Comment by christopherpickering** [comment]
The rule is a preference. If you run an html formatter the empty lines will normally be removed.

If you are using djlint for formatting you can use the "blank lines after tag" option to insert blank lines. Just be careful using it on "endif" if you have if's inside attributes.
