### ISSUE TITLE
[BUG] [Formatter] object/array variable whitespace is removed

### ISSUE THREAD

**Issue by tomdavies** [Riverside-Healthcare/djLint#370]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: macOD 12.5.1
 - Python Version 3.10.6
 - djLint Version 1.12.2
 - template language: e.g. Twig

## Issue

All whitespace is removed from multi-line `{% set = {} %}` statements (e.g when declaring a nested object), and also from object function parameters formatted in the same way.

## How To Reproduce

Given the input:

```twig
{% set foo = {
  bar: {
    baz: {
      cux: 1
    }
  }
} %}

{% set fruit = [
  'Apples', 
  'Pears',
  'Bananas'
] %}

{{ myfunc({
  bar: {
    baz: {
      cux: 1
    }
  }
})
```

I get the output

```twig
{% set foo = {
bar: {
baz: {
cux: 1
}
}
} %}
{% set fruit = [
'Apples',
'Pears',
'Bananas'
] %}
{{ myfunc({
bar: {
baz: {
cux: 1
}
}
})


```
When I expect indentation to be applied to the keys/values in my variable declarations per my `.djlintrc`:

```json
{
  "extension": "twig",
  "profile": "nunjucks"

}
``` 

Thanks so much for your work on djLint!

**Comment by christopherpickering** [comment]
similar case as #287

**Comment by oliver-schulz** [comment]
Hello we have the same problem here when using `djlint` with the same configuration. Is there a way to exclude theses from linting through the config file?

Before:
```
<div class="w-full">
  {{
    sylius_template_event(
      'sylius.shop.cart.summary',
      {
        cart: cart
      }
    )
  }}
</div>
```

After:
```
<div class="w-full">
    {{
    sylius_template_event(
    'sylius.shop.cart.summary',
    {
    cart: cart
    }
    )
    }}
</div>
```

**Comment by christopherpickering** [comment]
@oliver-schulz sorry I missed the question about excluding. If you didn't already find it, you can do it like:

```html
<div class="w-full">
    {# djlint:off #}
    {{
    sylius_template_event(
        'sylius.shop.cart.summary',
        {
        cart: cart
        }
    )
    }}
    {# djlint:on #}
</div>
```

**Comment by christopherpickering** [comment]
Link to twig expressions: https://twig.symfony.com/doc/3.x/templates.html#expressions

**Comment by christopherpickering** [comment]
@tomdavies @oliver-schulz thanks for waiting on this, the next release will fix both examples you provide :)

Just noting in @tomdavies there was a typo, the closing `}}` were missing. I assumed it was an accident and made djlint format only full tags ;)

**Comment by tomdavies** [comment]
Thanks @christopherpickering much appreciated! Will check this out. And yes, that was a typo in my crumby example code 😄
