### ISSUE TITLE
[FEATURE] Specify source path in config file

### ISSUE THREAD

**Issue by ylac** [Riverside-Healthcare/djLint#371]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request
Hi,

We would like to request specifying the source path in the config file. This would make it a bit easier to maintain config in CI.

**Comment by christopherpickering** [comment]
hey @ylac thanks! Do you know other tools with that option I can take a look at?

**Comment by ylac** [comment]
Hi @christopherpickering, sure `mypy` is one of the tools we use that allow this. They allow a `files` param in the config file.

**Comment by christopherpickering** [comment]
Thanks!

**Comment by christopherpickering** [comment]
I've added this in for the next release. So in your `.djlintrc` you can add something like this:
```json
{
    "indent":"2",
    "files": [
        "index.html"
        ]
}
```

and then using it with `djlint - --lint`. Note the `-` for the source.

Thanks @ylac !

**Comment by ylac** [comment]
Awesome thanks so much ❤️ !
