### ISSUE TITLE
[FEATURE] H030,H031 should not be an error

### ISSUE THREAD

**Issue by danielniccoli** [Riverside-Healthcare/djLint#373]
- [x ] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x ] I've read the [docs](https://djlint.com)

## Feature Request
H030 and H031 should not be an error. At the very most, they should be warnings, but I would consider them even less, like an info or something. Meta descriptions and keywords are completely optional and many websites do not even use them, which is completely fine.

**Comment by christopherpickering** [comment]
Hi @danielniccoli, they are mentioned as considerations and can be disabled here: https://djlint.com/docs/configuration/.
