### ISSUE TITLE
[BUG] [Formatter] --quiet is very verbose when combined with --check

### ISSUE THREAD

**Issue by NVolcz** [Riverside-Healthcare/djLint#374]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Ubuntu 22.04.1 LTS
 - Python Version: 3.10.4
 - djLint Version: 1.12.1
 - template language: nunjucks

## Issue
Running `djlint . --extension=.njk --quiet --check` outputs the templates validated which makes the output unnecessarily verbose.

## How To Reproduce
`djlint . --extension=.njk --quiet --check`

**Comment by christopherpickering** [comment]
Hi @NVolcz right now the quite option is only disabling the file diff when you using the src option. If you are using stdin (like the editor plugins) the output contains less.

What did you have in mind that the `--quiet` option would do besides disabling the diff?

**Comment by christopherpickering** [comment]
I think I'm following you now... the output of `--check --quiet` is also listing files that don't need to be updated... I'm going to do a new release that cleans up the output with the --quiet flag.


![image](https://user-images.githubusercontent.com/17788706/192265142-36450ca3-4401-4e2c-a63d-fc419cb57500.png)

The `--quiet` option with the `--check` option is printing a list of files that would be changed.

**Comment by NVolcz** [comment]
Thanks for fixing and taking the time to figure out what I meant with this issue and sorry for being responsive.

**Comment by christopherpickering** [comment]
Np, thank you!
