### ISSUE TITLE
[FEATURE] Raise an error when `{% endif }%` is used instead of `{% endif %}`

### ISSUE THREAD

**Issue by cclauss** [Riverside-Healthcare/djLint#385]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Raise an error when `{% endif }%` is used instead of `{% endif %}`

**Comment by christopherpickering** [comment]
I think a pretty simple regex will cover this one: `{%(?:(?!%}).)*}%`.
And message: `Did you intend to use {% ... %} instead of {% ... }%?`
