### ISSUE TITLE
[BUG] [Formatter] Hanging Indent is Off With Mismatched Inline Tags in Some Cases

### ISSUE THREAD

**Issue by BrokenEagle** [Riverside-Healthcare/djLint#387]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info

 - OS: Windows 8.1
 - Python Version (3.7.9)
 - djLint Version (1.14.2)
 - template language: jinja

## Issue

Having mismatched inline tags inside a `<li>` tag causes the closing `</li>` tag to have an extra indent.

## How To Reproduce

Example test file and configuration have been included at the end. When executing the command `djlint --check test.html` , it produces the following output.

```
@@ -21,20 +21,20 @@

 <ul>
     <li>
         <span>C</span> <a>D</a> <strong>Q</strong>
-    </li>
-</ul>
-<ul>
-    <li>
-        <a>2</a> <span>3</span>
-    </li>
-</ul>
-<ul>
-    <li>
-        <span>G</span> <strong>H</strong>
-    </li>
-</ul>
-<ul>
-    <li>
-        <strong>G</strong> <span>H</span>
-    </li>
-</ul>
+        </li>
+    </ul>
+    <ul>
+        <li>
+            <a>2</a> <span>3</span>
+            </li>
+        </ul>
+        <ul>
+            <li>
+                <span>G</span> <strong>H</strong>
+                </li>
+            </ul>
+            <ul>
+                <li>
+                    <strong>G</strong> <span>H</span>
+                    </li>
+                </ul>
```

It seems like when there is more than one type of inline tag in an `<li>` block, it causes the indent problem to occur. However, if any of the inline tags has more than one occurrence on the same line, then the problem does not occur, even if there are other inline tags which only have one occurrence.

## Files used

- [.djlintrc](https://drive.google.com/uc?export=download&id=11t5wCbB04Wed2GS7GUqqRhDs_LGC3RY9)
- [test.html](https://drive.google.com/uc?export=download&id=1MtMAqiUXI-ifC3y5MjP6vjU-Yl5g10-_)

**Comment by christopherpickering** [comment]
Thanks! seems like almost the same as I fixed yesterday here https://github.com/Riverside-Healthcare/djLint/commit/4ac5fd0da87bc0bf3ee49c5007db64ea4e34f46d, but the inverse.
