### ISSUE TITLE
[BUG] H015 triggered by HTML in JS strings

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#41]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3.7
 - djLint Version: 0.4.9

## Issue
The snippet below cause `H015 Follow h tags with a line break.`  This could be OK, if it is intentional that HTML within JS strings are processed, but it seems this is a strange and problematic windy path to go down.

## How To Reproduce

```html
<script>
    var template = '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>';
</script>
```

**Comment by christopherpickering** [comment]
To fix this I think I can borrow some logic from the reformatted, which has a snippet to ignore code between certain tags. I'll check it out soon.
