### ISSUE TITLE
[BUG] [Formatter] Extra indentation

### ISSUE THREAD

**Issue by monosans** [Riverside-Healthcare/djLint#425]
## System Info

 - OS: Arch Linux
 - Python v3.10.8
 - djLint v1.19.0
 - Template language: django

## Issue

The last line should not be indented. The bug appeared in djLint v1.19.0, it doesn't exist in v1.18.0.

```django
{% load i18n %}
{% block content %}
    <span></span>{% blocktrans %}<div></div>{% endblocktrans %}
    {% endblock content %}
```

**Comment by christopherpickering** [comment]
@monosans thanks, I'll check it out.
