### ISSUE TITLE
[BUG] [Formatter] `format_attribute_template_tags` option makes URLs in tags attributes unreadable

### ISSUE THREAD

**Issue by monosans** [Riverside-Healthcare/djLint#427]
- [X] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [X] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [X] I've read the [docs](https://djlint.com)

## System Info
 - djLint v1.19.1

## Issue

`format_attribute_template_tags` option makes URLs in tags attributes unreadable.

## How To Reproduce

```django
<a class="page-link" href="?{% if foo %}foo={{ foo }}&amp;{% endif %}bar={{ bar }}"></a>
```

This is reformatted like this:

```django
<a class="page-link"
   href="?
         {% if foo %}
           foo={{ foo }}&amp;
         {% endif %}
         bar={{ bar }}"></a>
```

This makes the resulting URL unreadable and ugly due to spaces. Example: `http://127.0.0.1:8000/?%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20foo=foo&%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bar=bar`
I suggest making `format_attribute_template_tags` ignore the formatting of attributes such as `<form>`'s action, `<a>`'s href, `<img>`'s and `<video>`'s src, and maybe a few others I forgot about.

### Config

```toml
[tool.djlint]
format_attribute_template_tags = true
```

**Comment by christopherpickering** [comment]
@monosans I rewrote the regex for the attribute parsing so that it will give me back groups : name, value, or just value. I need to rewrite the attirubute formatting code, hopefully next week, to fix this problem.
