### ISSUE TITLE
[BUG] [Formatter]

### ISSUE THREAD

**Issue by rjbullock** [Riverside-Healthcare/djLint#445]
- [x ] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [ x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [ x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 10
 - Python Version (`3.10.8`)
 - djLint Version (``1.19.4`)
 - template language: Django HTML

## Issue
When using a custom block tag with a <script> tag inside of it, formatting fails:
```
{% block extra_js %}
    {% compress parcel file todo %}
        <script type="text/javascript" src="{% static 'bundle.js' %}"><script>
   {% endcompress %}
  {% compress parcel file myfile  %}
        <script type="text/javascript" src="{% static 'test.ts' %}"></script>
    {% endcompress %}
{% endblock extra_js %}
```

Results in:

```
{% block extra_js %}
    {% compress parcel file todo %}
        <script type="text/javascript" src="{% static 'bundle.js' %}">
            < script > {
                    % endcompress %
                } {
                    % compress parcel file myfile %
                } <
                script type = "text/javascript"
            src = "{% static 'test.ts' %}" >
        </script>
{% endcompress %}
{% endblock extra_js %}
```
I have added "compress" to my custom blocks config.
## How To Reproduce
See code above.

**Comment by christopherpickering** [comment]
Thanks! your first <script> closing tag is missing the `/` before `>`. Does that make it work any better?

![image](https://user-images.githubusercontent.com/17788706/199768529-a4363e74-60f4-4ba1-a200-fc72b506a39c.png)

**Comment by christopherpickering** [comment]
no problem, do you have the js-formatting enabled? I wonder why everything was messed up inside the script. it looks like it was trying to format everything as js.
