### ISSUE TITLE
issue with alpineJS tags

### ISSUE THREAD

**Issue by TonisPiip** [Riverside-Healthcare/djLint#448]
- [X] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Issue
Updated from 18 to 19, and now djformatter is removing @ and : from http tags ID `<button :class="clicked && 'clicked'" @click="clicked=true"/>` is being refomatted to `class` and `click`, 

I don't see any reason for this in the change log or a setting to prevent this new formatting

**Comment by christopherpickering** [comment]
Hey @TonisPiip ,

Can you send a more complete in/out, your OS, full djlint version and your config? I cannot reproduce from this - 


![image](https://user-images.githubusercontent.com/17788706/200245896-d98591c8-e743-44f8-a6af-2a674c848fcc.png)

**Comment by TonisPiip** [comment]
Yes, will do.

**Comment by christopherpickering** [comment]
@oscarsiles ah ok, thanks for the example!

**Comment by TonisPiip** [comment]
Still need my version and conf settings or with the multi line example, were you able to re-create. The version is the latest,

**Comment by christopherpickering** [comment]
Here's a link to what is valid now... allowed attribs to start with `@` or `:`.
https://github.com/Riverside-Healthcare/djLint/blob/6c2d843c2f4fb1dd482a5fde36a56f17869b7449/tests/test_html/test_alpinejs.py#L27
