### ISSUE TITLE
[BUG] javascript: href triggers D018

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#45]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version: 0.4.9

## Issue
The following html triggers D018 "Internal links should use the {% url ... %} pattern."  These are not internal links.

It would be helpful to have a separate rule to prevent using `<a href="javascript:..">` which typically should be replaced with onclick and a real href for javascript disabled browsers.  Then I can disable only that rule (until I can fix the source code), while getting the benefit of D018.

## How To Reproduce
```html
<a href="javascript:abc()">{% trans "def" %}</a>
```

**Comment by christopherpickering** [comment]
Nice, thanks, I think I can update the regex to something like this
```
<(?:a|div|span|input)\s+?[^>]*?(?:href|data-url)=[\"|'](?!(?:https?://)|javascript|on\w+:)[\w|/]+
```
which should make all the inline javascript events acceptable. I can put a rule in for the "javascript"
