### ISSUE TITLE
[FEATURE] Indent custom block form_start in Twig

### ISSUE THREAD

**Issue by lukepass** [Riverside-Healthcare/djLint#476]
- [X] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [X] I've read the [docs](https://djlint.com)

## Feature Request

Hello, I tried using the `custom_blocks` and `custom_html` configuration parameters but I couldn't get the indentation to work when using `form_start` (a Symfony helper). How can I indent this with djLint?

```
{{ form_start }}
    {{ form_widget(form) }}
    <!-- Other -->
{{ form_end }}
```

My configuration:

```
{
  "extension": "html.twig",
  "profile": "nunjucks",
  "custom_blocks": "form_start,form_end",
  "custom_html": "turbo-frame"
}
```

Thanks!

**Comment by christopherpickering** [comment]
Hi @lukepass this syntax isn't curretly supported > when hugo support is added then it should work. 
currently only `{% ... %}` tags can be used for indent blocks but w/ hugo we should be able to do `{{ ... }}` indent blocks.

**Comment by lukepass** [comment]
Hello and thanks for the answer! What is hugo support?

**Comment by lukepass** [comment]
I am using Twig (with Symfony).
The `{{` syntax is for outputting things and the `{%` is for other things. For example:

```
{% set test = 'Test' %}
<p>{{ dump(test) }}</p>
```

**Comment by christopherpickering** [comment]
Thanks!

**Comment by lukepass** [comment]
Hello, is there any news about this issue?

Thanks!

**Comment by lukepass** [comment]
Yes, you can try the official Symfony Demo project which has a lot of recommended practices, here you can find a file containing `{{ form_start(form) }}` indented:

https://github.com/symfony/demo/blob/main/templates/user/edit.html.twig

Thanks.

**Comment by christopherpickering** [comment]
@lukepass I finally read the symfony docs and reallized that this is the only tag they have in `{{ }}` double curly. I will add it in the next release.
