### ISSUE TITLE
[FEATURE] H019 href="#"

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#48]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

I think  `href="#"` should also be H019.  I cant think of any reason it might be better as a separate linter rule.

I can probably do this one myself easily enough, and this would be a good one to cut my teeth on, provided you agree on it.

**Comment by christopherpickering** [comment]
Yes please, I'd appreciate a pr :) I use https://regex101.com or https://pythex.org for testing.

**Comment by jayvdb** [comment]
One reason to create a new rule would be to have a different error message, as `Replace 'javascript:abc()' with on_ event and real url.` is not really appropriate.  Perhaps `Replace href "#" with explicit target, such as "#top".`

**Comment by christopherpickering** [comment]
I think having a "#" is ok, we should just exclude it in the regex. For example, some tab implementations use "#" as the href and another field to identify the tab.

**Comment by christopherpickering** [comment]
2a85e0d
