### ISSUE TITLE
[FEATURE] Removing extra whitespace in formatter

### ISSUE THREAD

**Issue by luxcem** [Riverside-Healthcare/djLint#485]
- [X] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [X] I've read the [docs](https://djlint.com)

## Feature Request

I'm working on a new formatter for removing or adding extra whitespace in template tags and variables 

Examples:
```
{{  name }} -> {{ name }}
{{something}} -> {{ something }}
```

The branch is there: https://github.com/Riverside-Healthcare/djLint/compare/master...luxcem:feat/whitespace-clean

It's rather simple but I am unsure if there are any edge cases where the regular expression will not work as intended.

It's matching `"{{\s*(.*?\S)\s*}}"` and returning `{{ \1 }}`

**Comment by christopherpickering** [comment]
@luxcem feel free to start a pr and we can continue discussion on it 👍🏽
