### ISSUE TITLE
[BUG] [Formatter] long textarea in twig - line wrapping does not work

### ISSUE THREAD

**Issue by palansher** [Riverside-Healthcare/djLint#486]
## Issue

Your Djlint becomes better and better. Thank you!

## How To Reproduce

I cannot reformat such long lines 

```
<textarea type="textarea" id="messageContent" name="adContent" maxlength="300" class="form-control" rows="10">{{ adContent|default }}</textarea>

```

for like this:
```
<textarea 
               type="textarea" 
               id="messageContent" 
               name="adContent" 
               maxlength="300"  
               class="form-control" 
               rows="10">
               {{ adContent|default }}
</textarea>
```
It still one long line.
Same time, the long 'inputs' and 'divs' are wrapped well.

Please give your helping hand!

---

BTW, 

By, according to my observations, for textareas

this style
```
<textarea 
               content</textarea>
```
is more prefferable then this

```
<textarea 
               content
</textarea>
```
Because in the second variant the browser adds extra ugly  <CR/LF> trash to the end of content of textarea field.
It happens  when we have the combination of next three consistently: "content text" + line feed + "</textarea>".
So, the middle line feed makes the problem.

---

my conf:

.djlintrc
```
{
    "ignore": "H021,H030,H031,H017,H023,H014,H006",
    "extension": "twig",
    "indent": "4",
    "profile": "nunjucks",
    "format_attribute_template_tags": false,
    "max_line_length": "110",
    "max_attribute_length": "100",
    "preserve_blank_lines": "true"
}
```

- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: e.g. ubuntu 20.04
 - Python Version 3.8.10
 - djLint Version 1.19.7
 - template language: twig

**Comment by palansher** [comment]
> 🎉 This issue has been resolved in version 1.19.8 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/djlint/v/1.19.8)
> * [GitHub release](https://github.com/Riverside-Healthcare/djLint/releases/tag/v1.19.8)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Hello Chris!

Unfortunately, no change for textarea.

```
vladp@dev:~$ djlint --version
djlint, version 1.19.8
```

This code 

```
<textarea type="textarea" id="messageContent" name="adContent" maxlength="300" class="form-control" rows="10">{{ adContent|default }}</textarea>
```

is reformatting to one line back even if I format it manually and the settings are:

```
"max_line_length": "110",
"max_attribute_length": "100",
```

I extracted this textarea attribute alone to separate file. No Changes.

**Comment by palansher** [comment]
Even out of VS code extension:

```
djlint --reformat test.html.twig 

Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


0 files were updated.

✔ ~/dev/gtdev-advert/templates/admin/app [advert|✚ 7…3] 
15:34 $ cat test.html.twig 
<textarea type="textarea" id="messageContent" name="adContent" maxlength="300" class="form-control" rows="10">{{ adContent|default }}</textarea>
```

**Comment by christopherpickering** [comment]
hmm, its odd, I will check it out. The new test is passing nicely.

**Comment by palansher** [comment]
BTW: 
I just  noticed that my 'type="textarea"' inside <textarea>  tag is non-standard, according https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea.

I removed it and  .. no changes.

**Comment by christopherpickering** [comment]
no problem, we don't check for anything being standard except for changing case ;)

**Comment by christopherpickering** [comment]
I tried it out in the [online demo](https://djlint.com/demo/) and it is working:

![image](https://user-images.githubusercontent.com/17788706/208136888-ce7913b4-1bd5-4340-b80e-32e502b9c371.png)

can you send more surrounding html or a full file?

**Comment by palansher** [comment]
Holy cow, you have demo page!! 

hope, files can help:
[files.zip](https://github.com/Riverside-Healthcare/djLint/files/10247212/files.zip)

**Comment by palansher** [comment]
hmm, I have cleaned up config file and vua-la, it formats well!!!

But I see nothing illegal inside it (included in zip above).

**Comment by christopherpickering** [comment]
thanks! I'll check it out!

**Comment by christopherpickering** [comment]
I think I found the bug.. I'll see about getting a change out soon.

the `--check` flag + stdin was not writing the formatted code back and just retuning the original.

**Comment by palansher** [comment]
Alas! the same:

```
21:08 $ djlint --reformat test.html.twig 

Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


0 files were updated.

✔ ~/dev/gtdev-advert/templates/admin/app [advert|✚ 12…5] 
21:08 $ djlint --version
djlint, version 1.19.9
✔ ~/dev/gtdev-advert/templates/admin/app [advert|✚ 12…5] 
21:08 $ cat test.html.twig 
<textarea type="textarea" id="messageContent" name="adContent" maxlength="300" class="form-control" rows="10">{{ adContent|default }}</textarea>
✔ ~/dev/gtdev-advert/templates/admin/app [advert|✚ 12…5] 
```

**Comment by christopherpickering** [comment]
ty, will keep looking :) Your bugs always escape..

**Comment by christopherpickering** [comment]
@palansher try reducing the `max_attribute_length` to something smaller, or even 0 if you want attributes to always be formatted.

```json
{
    "ignore": "H021,H030,H031,H017,H023,H014,H006",
    "extension": "twig",
    "indent": "4",
    "profile": "nunjucks",
    "format_attribute_template_tags": false,
    "max_line_length": "110",
    "max_attribute_length": "50",
    "preserve_blank_lines": "true"

}
```
will make it format.

**Comment by christopherpickering** [comment]
@palansher hope things are well, haven't heard from you here in a while 😅 no bugs I guess 😁
