### ISSUE TITLE
[BUG] [Formatter] `--check` does reformat if file path contains `-`

### ISSUE THREAD

**Issue by vasekch** [Riverside-Healthcare/djLint#494]
`djlint, version 1.19.9`

## Issue

My file path is `./app-project/templates/main.html`, when I execute `--check` the file is formatted immediately and no output is given.

## How To Reproduce

`djlint --check <a path containing "-" character>`

## Possible solution

I've found this piece of code, where I believe something needs to be improved.

https://github.com/Riverside-Healthcare/djLint/blob/68da1186ed1b31f4693d416e30fcf30deffa4dbd/src/djlint/settings.py#L275

Not sure what is the idea behind `"-" in src`. Would it be sufficient if we just swap `"-" in src` for `src == "-"`? Or if more situations needs to be covered use `src in ("-", "--", ...)`.

Thanks.

**Comment by christopherpickering** [comment]
Thanks good catch. If you can send a pr for =='-' I think that is the best solution for now.
