### ISSUE TITLE
[BUG] --help extension default blank

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#50]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version: 0.4.9

## Issue
Running `djlint --help` shows a blank default for `-e`
```
-e, --extension TEXT  File extension to lint  [default: ]
```

**Comment by christopherpickering** [comment]
2a85e0d
