### ISSUE TITLE
[BUG] [Formatter] Reformat on Windows causes files to be changed to CRLF line endings

### ISSUE THREAD

**Issue by aarongoldenthal** [Riverside-Healthcare/djLint#502]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 10 (21H2)
 - Python Version (``python --version``): 3.10.8
 - djLint Version (``djlint --version``): 1.19.9
 - template language: nunjucks

## Issue

When running `djlint --reformat .`, djLint notes that no files were updated, but on Windows all "formatted" files are changed from LF line endings to CRLF. When the same files are checked/linted (`djlint --check --lint .`), djLint finds no errors and notes no files would be updated.

When running against the same files on Linux (I tested in a `python:alpine` container), the line endings are not changed.

Normally I use VSCode with both the djLint and EditorConfig extensions configured for formatting on save, and in that case it appears the EditorConfig settings are applied last (so in my case the line endings are not changed since all are set to LF).

For example:

```ps
PS C:\test> djlint --check --lint .

Checking and Linting 5/5 files »»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»» 00:00     


0 files would be updated.
Linted 5 files, found 0 errors.

PS C:\test> djlint --reformat .

Reformatting 5/5 files »»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»» 00:00     


0 files were updated.
```

But the 5 files were all changed from LF to CRLF.

## How To Reproduce

Create a nunjucks file with LF line endings and run `djlint --reformat .`.

## Recommendations

- I propose that ideally djLint wouldn't change the line endings of a file.
- If djLint does intentionally change the line endings when reformatting:
  - The console output should reflect that changes were made
  - It would be helpful to have a configuration setting to either control the line endings or disable
  - The behavior should be documented

**Comment by christopherpickering** [comment]
hmm good point. Right now the line endings are all `\n`, as djlint splits the lines for formatting and then rejoins them.

Do you have an idea of a good way to see what the system line ending should be?

**Comment by aarongoldenthal** [comment]
My python's pretty rusty, but looking at the code and the docs...

When [writing the file](https://github.com/Riverside-Healthcare/djLint/blob/3e7451a5a6b14ec93c496d7585c4d66858aaeef0/src/djlint/reformat.py#L38), `write_text` accepts an optional [`newline` parameter](https://docs.python.org/3/library/pathlib.html#pathlib.Path.write_text) (as of python 3.10), and [the docs say](https://docs.python.org/3/library/functions.html#open):

> When writing output to the stream, if newline is None, any '\n' characters written are translated to the system default line separator, [os.linesep](https://docs.python.org/3/library/os.html#os.linesep). If newline is '' or '\n', no translation takes place. If newline is any of the other legal values, any '\n' characters written are translated to the given string.

Which sounds like it explains the behavior. So, I'm wondering if it's as simple as passing '' to the `newline` parameter for no translation?

**Comment by aarongoldenthal** [comment]
Thinking a little more about it, that probably doesn't fully solve the problem if line endings are being normalized when the file is read, it would likely just output everything with \n.

If the file were opened without normalizing line endings, that sounds like it would make processing overly complicated. I guess you could open up the file, or maybe just part of the file, a second time without normalizing line endings just to check the original, which also doesn't sound like the right answer (possible, but performance implications if nothing else).

Maybe the best answer is a configuration option that either keeps line endings with the system default (as is), or has options to explicitly state the line ending, and just leave it up to users to configure. One could argue there's benefits in specifying it, especially on Windows where you could have differences between files, to ensure that you're getting a consistent result.

**Comment by christopherpickering** [comment]
For a short term change, we could only rewrite the file if something has changed. Right now we are rewriting the file 100% of the time when --reformat is called.

**Comment by christopherpickering** [comment]
It looks like black handles it by checking the first line ending in the file. https://github.com/psf/black/issues/3255

This is probably the best, safest, and most reliable solution if we will keep supporting several py versions.
