### ISSUE TITLE
[FEATURE] Inplace formatting

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#51]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Most formatters provide in-place editing, replacing the file(s) with the updated formatted file.

**Comment by jayvdb** [comment]
Ohhh, this is the default, and `--quiet` is needed to hide the production of diffs on the console.  I think the help / docs could be a bit clearer about this.

**Comment by christopherpickering** [comment]
Thanks, I updated the docs. Feel free to recommend any other changes to wording.
- ``--check`` > review what might change
- ``--reformat`` > accept changes and update file
- ``--reformat --quiet`` > accept changes and update file without showing diff
