### ISSUE TITLE
[BUG] [Linter] H017 is opposite of W3C recommendation

### ISSUE THREAD

**Issue by tbrlpld** [Riverside-Healthcare/djLint#517]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Issue

Rule H017 flags instances of void elements what are not self-closing. 

Running code that does add the self-closing slash to void elements through the [W3C validator](https://validator.w3.org) will be flagged with issues because trailing slashes have no effect. 

See also: https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#promoting-the-right-mental-model-for-void-elements

I know the rule could be deactivated in config, but it seems confusing to have a rule that violates, or at least is counter, to the official recommendation/standard. 

***

On a totally different note: Thank you so much for this project!

**Comment by christopherpickering** [comment]
Thanks for the feedback!

the w3c is flagging it as info, not an issue.. I don't intend to change that rule - as you say it can be disabled in the config and is a preference. On the side, and not that it matters to this project, prettier inserts the closing` />` by default, and react requires it.

**Comment by tbrlpld** [comment]
Fair points. The W3C page actually calls out Prettier too 😆
