### ISSUE TITLE
[BUG] [Formatter] Nunjucks seem to be broken

### ISSUE THREAD

**Issue by hihahihahoho** [Riverside-Healthcare/djLint#518]
i'm using online demo, the result:

![image](https://user-images.githubusercontent.com/29968144/212464607-b80680c2-05e6-4929-94fe-f0a8774d6272.png)

what i'm expected:
![image](https://user-images.githubusercontent.com/29968144/212464624-7a926c89-6528-413d-83d2-42f9c1441bf6.png)

**Comment by hihahihahoho** [comment]
a little bit off topic, but i use chat gpt to format it, and it gave the perfect result lol, better than any nunjucks formatter i tried:
![image](https://user-images.githubusercontent.com/29968144/212464776-7ddcfcf7-f77c-4a19-ad22-8568ceabf161.png)

**Comment by christopherpickering** [comment]
Thanks, it would be helpful to past in the actual code.

Currently `set` is not supported.
