### ISSUE TITLE
Drop importlib-metadata from deps

### ISSUE THREAD

**Issue by Mogost** [Riverside-Healthcare/djLint#523]
I see only one usage of importlib-metadata in code and it's in test. Could we drop it and move to dev deps?

https://github.com/Riverside-Healthcare/djLint/blob/14e8be4c0722dba2814af0d29bc85d428ea5e11e/tests/test_djlint/test_djlint.py#L19-L23

Also, it's not required after python 3.8 and we should not install it
https://github.com/Riverside-Healthcare/djLint/blob/14e8be4c0722dba2814af0d29bc85d428ea5e11e/pyproject.toml#L37

**Comment by christopherpickering** [comment]
Yep, good suggestion. I added it in after one of my poetry envs uninstalled it in py39 somehow.
