### ISSUE TITLE
[BUG] text in <style> indented too much

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#54]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version: 0.4.9

## Issue
I am encountering this unacceptable reformatting within `<style>`.

```diff
 {% block headinclude %}
     <style>
         {# override to fix text all over the place in media upload box #}
-        .k-dropzone .k-upload-status {
-            color: #a1a1a1;
-        }
+                                                        .k-dropzone .k-upload-status {
+                                                            color: #a1a1a1;
+                                                        }
     </style>
 {% endblock %}
```

## How To Reproduce

If the above isnt reproducible, I need to dig into my `element_quick_entry.html` a bit more to isolate the problem.

**Comment by christopherpickering** [comment]
I'm thinking its the comment inside the style tag that is throwing it off. I'll check that out!
