### ISSUE TITLE
[QUESTION] [Formatter] HTML Pre tag formatting question

### ISSUE THREAD

**Issue by RKMagenta** [Riverside-Healthcare/djLint#540]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: ubuntu 22.04.1
 - Python Version: 3.9
 - djLint Version: 1.19.13
 - template language: django

## Issue

When running the formatter over my templates, the pre-element specifically has some errors. The formatter indents the pre element, but not its contents or the end /pre-element.

## How To Reproduce

Running the formatter over a pre-element and its content, the content should be on a different line, same for the /pre-element.

**Comment by christopherpickering** [comment]
Hi @RKMagenta, the contents of pre are ignored, as changes to whitespace are shown in the resulting HTML.

Please post an example if you feel there should be formatting changes.

**Comment by christopherpickering** [comment]
Closing for now. Please reply or open a new issue with a code snippet.
