### ISSUE TITLE
[BUG] [Formatter] Single Quote is deleted inside {{ block }} when element has multiple attributes

### ISSUE THREAD

**Issue by tye-shutty** [Riverside-Healthcare/djLint#544]
- [x ] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [ x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [ x] I've read the [docs](https://djlint.com)

## System Info

-   OS: ubuntu 22.04
-   Python 3.10.6
-   djlint, version 1.19.14
-   Jinja

## Issue

Single quote gets deleted, causing JS error, in this case:

```
<div onclick="location.href='{{ url_for('my_page') }}'" data-thing="my-data"></div>
```
command
```
djlint  --profile=jinja --reformat templates/product/formatter_failures.html
```
result
```
<div onclick="location.href='{{ url_for('my_page') }}"
     data-thing="my-data"></div>
```

**Comment by christopherpickering** [comment]
Do you have anything else in the file? I can't reproduce it with just that snippet -

![image](https://user-images.githubusercontent.com/17788706/217943158-51b501ac-e400-4210-b64e-754fa33a418a.png)

**Comment by tye-shutty** [comment]
![image](https://user-images.githubusercontent.com/35602190/217944965-0ecf0f89-bc2f-4b14-8975-dc3b770aa131.png)


nothing else

**Comment by christopherpickering** [comment]
Shucks, I was on a mac, I'll try on ubuntu.

**Comment by christopherpickering** [comment]
I tried this through docker and still cannot reproduce:

```bash
docker run -i -t ubuntu /bin/bash
apt-get update; apt-get install python3 python3-pip
pip3 install djlint
echo "<div onclick=\"location.href='{{ url_for('my_page') }}'\" data-thing=\"my-data\"></div>" > test.html
djlint --profile=jinja test.html --check
```

![image](https://user-images.githubusercontent.com/17788706/229900751-2f7f78d3-4124-4f80-87db-5bd7b029e52f.png)

Possible a later version of djlint has fixed this already.

I'm gonna close for now, but I will reopen this if you can put me good steps like this to reproduce it somehow.
