### ISSUE TITLE
[FEATURE] Add a --exclude parameter to CLI

### ISSUE THREAD

**Issue by frague59** [Riverside-Healthcare/djLint#558]
Hi, 

I've an issue with a generated HTML file from `rollup-plugin-visualizer`: this file is generated when I build my [vite](https://vitejs.dev/) package, and linting fails on it. I've added the file in the pyproject.toml file, but it still fails.

The file is conveniently avoided in pre-commit hook.

- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Add an `--exclude` parameter to the CLI tool to avoid this issue.

Could be "cumulative" with the pyproject.toml settings, and may be used multiple times:

```sh
$ djlint --exclude ./src/assets/stats.html --lint --profile django ./src
```

Thanks !

**Comment by christopherpickering** [comment]
Hi @frague59, so if I understand right you are trying to exclude the file already in you `pyproject.toml` file? Can you share the setting you have tried there? Thanks!

**Comment by frague59** [comment]
From `pyproject.toml`

```toml

[tool.djlint]
indent = 2
profile = "django"
max_line_length = 120
ignore = "H031,H006,H017,H023"
exclude = "venv/*,src/bower/*,src/assets/*"
```

Maybe the `exclude` parameter docs is confusing...

Thanks !

**Comment by christopherpickering** [comment]
Thanks! I'll check it out!

**Comment by christopherpickering** [comment]
Hey @frague59 it looks like I need to update the docs.

Exclude should be a reg exp, the default is:

```py
default_exclude: str = r"""
            \.venv
            | venv/
            | \.tox
            | \.eggs
            | \.git
            | \.hg
            | \.mypy_cache
            | \.nox
            | \.svn
            | \.bzr
            | _build/
            | buck-out/
            | build/
            | dist/
            | \.pants\.d
            | \.direnv
            | node_modules/
            | __pypackages__
        """
```

while the extend_exclude is a comma separate list of folders/files that are pipe joined into a reg expression and combined with the default exclude. Try swapping your exclude to

```sh
extend_exclude = "src/assets/" 
```

Its safer to leave the default exclude as is and use the extend exclude option so that you don't have to re-invent the wheel on the exclude list.

does that work out better?

**Comment by frague59** [comment]
Hi, 

Thanks !

... look's like it works !

**Comment by christopherpickering** [comment]
ok cool! I'll leave this open as still the cli option would be nice.

**Comment by christopherpickering** [comment]
This is in the latest release. I'd recommend using --extend-exclude instead of --exclude.

**Comment by StevenMapes** [comment]
I'm struggling to get my docs folder to be ignored. I've tried setting it up in the .djlintrc, pyproject.toml and the .pre-commit-config.yaml as a --extend-exclude CLI switch but in all cases the additional path is ignored and the folder is scanned which makes it unusable when I rebuild my docs.

What's the correct way to implement this with 1.28.0?


.djlintrc = 
```
{
  "profile": "django",
  "ignore": "H030,H031,T003,H020,H023,H021,H006",
  "extend_exclude": "docs/",
}
```

pyproject.toml
```
[tool.djlint]
profile="django"
ignore = "H030,H031,T003,H020,H023,H021,H006"
extend_exclude="docs/"
```

pre-commit

```
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.28.0
  hooks:
    - id: djlint-django
      args: ["--profile", "django", "--ignore", "H030,H031,T003,H020,H023,H021,H006", "--extend-exclude", "docs/"]
```

**Comment by christopherpickering** [comment]
@StevenMapes can you open a new issue for this?

What is your folder structure?

For the pre-commit one, I'm not exactly sure what will happen, personally I would use the pre-commit exclude option.

For the other two I tested like this w/out a problem:

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/bdc1b588-0ce1-4d51-8112-6df4cfaa29be)

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/cdb80a0b-44a0-451f-aff9-a8eccca95dcf)

**Comment by StevenMapes** [comment]
Folder structure within the project is

```
- app1
- app2
- docs/_build/*.html
- docs/_templates/
- templates/*.html
- templates/<app folders>/*.html
- tests/
- manage.py
- .flake8
- .pre-commit-config.yaml
- pyproject.toml
```

In the end I got it working by using this in the pre-commit file to force it to just look at the central templates folder. 
```
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.28.0
  hooks:
    - id: djlint-django
      files: "templates"
```

All other methods of tying to use exclude or extend exclude were ignored other than manually running ```djlint --profile django --ignore H030,H031,T003,H020,H023,H021,H006 --extend-exclude docs/ ./``` from the terminal

**Comment by christopherpickering** [comment]
Ah thanks, so the cli command was working, but not the config file?

**Comment by christopherpickering** [comment]
I can't reproduce using pyproject.toml config either... if you can open an issue w/ an example repo that is busted I would greatly appreciate it.

**Comment by StevenMapes** [comment]
Yes the CLI works but when triggered by a pre-commit it does not pass the parameters in to the extend_exclude from the config files. It does pass in the ignore list as those warning are ignored.

Sadly the project I've noticed it on is for a client, is private, and is not hosted on github. I'll have to try creating a sample project but the docs folder was populated by sphinx

**Comment by StevenMapes** [comment]
I have a sample project I will create a ticket as it's replicating there

**Comment by StevenMapes** [comment]
Ticket #664  created with instructions on how to view the extend_exclude not working.

**Comment by lgarron** [comment]
I'm also seeing an issue where I can't manage to exclude a `.temp` and `node_modules` folder simultaneously. I was able to hack around this by passing both `exclude` and `extend_exclude`, but this doesn't generalize to more than 2 folders.

```toml
[tool.djlint]
exclude = "\\.temp"
extend_exclude = "node_modules"
```
