### ISSUE TITLE
[BUG] blank_line_after_tag not working inside blocks

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#56]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version: 0.4.9

## Issue
I have config `blank_line_after_tag = "load,extends,include,csrf_token,endblock,endwith"` , and I do see blank lines added after `load` and `include` when they are at the top level.

However when inside a `{% block %}...{% endblock %}` , the existing blank lines are being removed.

## How To Reproduce
```diff
@@ -1,25 +1,23 @@
 {% extends "administration/basemodal.html" %}
+
 {% load static %}

 {% block content %}
     {% load i18n %}
-
     {% trans 'Are you sure you want to delete' %} '{{ object }}'?
-    <br/><br/>
-
+    <br/>
+    <br/>
     <form action="" method="POST">
         {% include "administration/form.html" %}
-
         <div class="row">
         ...
```
If the above isnt reproducible, I need to dig into my `administration/templates/administration/delete.html` a bit more to isolate the problem.

**Comment by christopherpickering** [comment]
Thanks, it was setup to find tags that started on a new line only, without leading whitespace, but I think leading whitespace should be acceptable, and will fix your case.

If you have 
```
blank_lin_after_tag="endif"
```
and a statement like

<a class="{%if a%}b{%endif%}"></a>
{% if a %}
b
{% endif%}
```

Adding a line break on the first {% endif %} would be a problem.

I'll get an update together.
