### ISSUE TITLE
[BUG] [Linter]

### ISSUE THREAD

**Issue by marty0678** [Riverside-Healthcare/djLint#560]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 11 22H2
 - Python Version: 3.11.2
 - djLint Version: 1.19.15
 - template language: DjangoTemplates

## Issue
Specific linting rules as defined in the docs and this issue - https://github.com/Riverside-Healthcare/djLint/issues/113 do not seem to apply, as you can not filter out specific rules in the template.

## How To Reproduce
An example of a code block that I would expect to still display an H021 error for in-line styles, but it does not.  All linting rules appear to be ignored, regardless of the filter.
```
            {% comment %} djlint:off H025 {% endcomment %}
            <h1 style="margin: 0">
                Welcome to My Website
            </h1>
            {% comment %} djlint:on {% endcomment %}
```

## Contents of .djlintrc/pyproject.toml [tool.djlint]
```
{
    "blank_line_before_tag": "load,extends,include",
    "preserve_blank_lines": true,
    "max_line_length": "30",
    "max_attribute_length": "3",
    "format_js": true,
    "format_css": true
}
```
It appears to still happen if I clear out my config as well.

**Comment by christopherpickering** [comment]
Thanks! will get a fix for this out soon.

**Comment by marty0678** [comment]
Amazing thank you for the fast turn around!
