### ISSUE TITLE
[BUG] [Formatter]

### ISSUE THREAD

**Issue by nrnvgh** [Riverside-Healthcare/djLint#566]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: OSX 13.2.1
 - Python Version 3.10.2
 - djLint Version 1.19.15
 - template language: jinja

## Issue
Can't stop `{% for %}...{% endfor %}` block from being collapsed down to a single line.

### Slightly longer description
I'm attempting to use jinja2 to output YAML. I've inherited a stack of .j2 files with zero indentation for the `{% %}` control blocks and `djlint` seemed like a good tool to use to try and fix this. Because it's YAML, whitespace needs to be preserved. You may be saying to yourself "Yes, but there's a config parameter for that", however see below. 

## How To Reproduce
Here's my current `.djlintrc`:

    {
        "profile": "jinja",
        "preserve_leading_space": true
    }
 
Using `preserve_leading_space` is certainly acres better than not using it, however given this jinja snippet:

    - parent:
        child:
          var1: {{ some_var }}
          var2: {{ another_var }}
    {% if some_var > 1 %}
    {% if another_var > 10 %}
    {% if IGNORE is defined %}
          config:
            set:
              ignore:
    {% for ignored_item in IGNORE %}
                {{ ignored_item }}: {}
    {% endfor %}
    {% endif %}
    {% endif %}
    {% endif %}

...which will render this YAML:

    - parent:
        child:
          var1: 3
          var2: 12
          config:
            set:
              ignore:
                foo: {}
                bar: {}
                baz: {}

...`djlint --reformat` outputs this:

    - parent:
        child:
          var1: {{ some_var }}
          var2: {{ another_var }}
    {% if some_var > 1 %}
        {% if another_var > 10 %}
            {% if IGNORE is defined %}
          config:
            set:
              ignore:
                {% for ignored_item in IGNORE %}{{ ignored_item }}: {}{% endfor %}
            {% endif %}
        {% endif %}
    {% endif %}

...which outputs this (obvs invalid) YAML:

    - parent:
        child:
          var1: 3
          var2: 12
          config:
            set:
              ignore:
    foo: {}bar: {}baz: {}

I did try the `beast_mode` branch just for grins, and that's...much worse. =)

**Comment by christopherpickering** [comment]
@nrnvgh I'm thinking what you need to do is set the max line length to 0 to force everything to wrap.

Here's a pic from the demo https://djlint.com/demo/:

![image](https://user-images.githubusercontent.com/17788706/221876196-6ca9eda2-07e5-489d-ba5a-8a43fb073468.png)


Does that come how you need?

**Comment by nrnvgh** [comment]
Thanks for the quick response. The problem with your proposed solution is that the lines which reads...

`{{ ignored_item }}: {}`

...is brought back to the start of the line; the rendered YAML needs to be:

    - parent:
        child:
          var1: my_var_1
          var2: my_var_2
          config:
            set:
              ignore:
                item1_to_ignore: {}
                item2_to_ignore: {}
                itemN_to_ignore: {}


...but with `max_line_length` set to `0`, I get:

    - parent:
        child:
          var1: my_var_1
          var2: my_var_2
          config:
            set:
              ignore:
    item1_to_ignore: {}
    item2_to_ignore: {}
    itemN_to_ignore: {}


Similarly (again, with `max_line_length` at `0`) djlint will reformat this:

          parent:
            mgmt:
              server:
    {% for server in entry.servers %}
                {{ server.ip }}:
                  port: {{ server.port }}
    {% endfor %}

...to this:

    parent:
            mgmt:
              server:
    {% for server in entry.servers %}
    {{ server.ip }}:
                  port: {{ server.port }}
    {% endfor %}

Which has both incorrectly tweaked indentation levels between `parent` and `mgmt` and the pulled-back representation for `{{ server.ip }}`

**Comment by christopherpickering** [comment]
ah I see, the leading space is not preserved on template syntax. That might be the best fix for this case - changing djlint to also keep indentation on lines that start w/ a template tag... if that is possible. I'll have to check out the code closely on this one :)

**Comment by christopherpickering** [comment]
@nrnvgh sorry for the delay on this. I should have an update out soon that will treat `{{ }}` tags as text and keep the leading spaces intact.

you should be able to use a config like
```json
{
    "profile": "jinja",
    "preserve_leading_space": true
}
```

**Comment by nrnvgh** [comment]
Preliminary testing looks good; I'll know more in a few days when I have a chance to use it against some gnarlier templates. Thanks!
