### ISSUE TITLE
[FEATURE] detect duplicate HTML attributes

### ISSUE THREAD

**Issue by GeorgeSchneelochVA** [Riverside-Healthcare/djLint#577]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Thanks for all the effort put into this useful tool. My feature suggestion: it would be nice if duplicate HTML attributes could be detected and warned about:

    <div class="a b" class="c d"></div>

At least on Chrome this will only count the first `class` attribute, and having two is probably an oversight.

**Comment by christopherpickering** [comment]
Excellent idea! This would be pretty easy if we had already upgraded to use the html parser, but we can probably pull it off with some regex + python like rule h025.

**Comment by christopherpickering** [comment]
@GeorgeSchneelochVA thanks, I'm adding rule H037 for this. It will be out in the next release.

**Comment by GeorgeSchneelochVA** [comment]
Thanks for your help!
