### ISSUE TITLE
[FEATURE] Implement rules of html-linter / Google Style Guide

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#59]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

https://pypi.org/project/html-linter/ is https://github.com/sk-/html-linter/ which is archived.

It linted against  https://google.github.io/styleguide/htmlcssguide.html and (vaguely) "some extra rules" from https://github.com/kangax/html-minifier , but some additional clarity may be found at [google cache of some webpage](http://webcache.googleusercontent.com/search?q=cache:nh2cZiK_bS4J:perfectionkills.com/experimenting-with-html-minifier/+&cd=1&hl=en&ct=clnk&gl=au)

**Comment by christopherpickering** [comment]
I've added in the rules we seemed to be missing. If something particular comes up open an issue and I'll add it in, or better yet, send over a pr with the new rule. :)
