### ISSUE TITLE
[BUG] [Formatter] Fix for #584 perpetually adds an empty line after front matter in nunjucks files

### ISSUE THREAD

**Issue by aarongoldenthal** [Riverside-Healthcare/djLint#596]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 11 22H2, Alpine Linux 3.17
 - Python Version (``python --version``): 3.10.10 (Windows), 3.11.3 (Linux)
 - djLint Version (``djlint --version``): 1.23.0
 - template language: nunjucks

## Issue

The fix for #584 in v1.20.0 adds an empty line after front matter in nunjucks files even if on exists. 

## How To Reproduce

Using the following as an example:

```
---
layout: layouts/base.njk
---

{{ content | safe }}

```

Running `djlint --reformat .` adds another empty line after the front matter, then running `djlint --check .` fails saying another blank line would be added, and the cycle repeats.

This worked properly in 1.19.17, but behaves as above starting in 1.20.0 and in all subsequent releases (currently through 1.23.0).

**Comment by christopherpickering** [comment]
@aarongoldenthal Thanks, do you have any config options set? I don't get this on mac, but will add a test and try on windows.

**Comment by christopherpickering** [comment]
Thanks, I'm guessing it is the preserve_blank_lines. I'll check it out and try to get a fix out shortly.
