### ISSUE TITLE
[BUG] [Formatter] djlint does not run with the --check or --reformat parameter

### ISSUE THREAD

**Issue by oliver-schulz** [Riverside-Healthcare/djLint#601]
- [ x ] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [ x ] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [ x ] I've read the [docs](https://djlint.com)

## System Info
 - OS: Ubuntu 22.04.2 LTS (gitlab pipline or local docker)
 - Python Version: `python 3.10`
 - djLint Version `djlint, version 1.23.1`
 - template language: twig (using the `nunjucks` profile)

## Issue
Since version `1.23.1` the djlint commands does not finish and it got stuck for hours and never finishes. What i discovered so far, when removing the `--check` parameter the command works. In our template folder are more than 300 twig files btw. At Version `1.23.0` everything was ok.

## How To Reproduce
```
djlint themes/ --profile=nunjucks --extension twig --reformat
```
OR
```
djlint themes/ --profile=nunjucks --extension twig --check
```

**Comment by christopherpickering** [comment]
@oliver-schulz thanks for reporting. Is there a public repo I can test with, or are you able to figure out which template is causing the hangup?

**Comment by oliver-schulz** [comment]
Thx for the hint. What i discovered so by checking some of theses folders step by step.

```
<div class="column"> {{
    'sylius.ui.change_address'|trans }}>
</div>
```
This breaks the reformat process, without error, because the `{{` starts at the end of the line and then the twig method was called.

Also this broke the process:
```
{%
endif
%}
```

I also had one syntax error when i had something like this:
```
<div class="foo"  'sylius.ui.change_address'|trans }}>
</div>
```
In this case i would have been expected an error or a warning, but in this case also the formatter stops working.

Does this help to improve the regex?

**Comment by christopherpickering** [comment]
Thanks! Yes, I will dig into this.

**Comment by christopherpickering** [comment]
@oliver-schulz Can you send a more complete file? When I just paste these in to a new file it works. You can email me or send it directly on discord if you like?

![image](https://user-images.githubusercontent.com/17788706/233122670-8bc6c8a8-006e-4269-bcbf-de394d813650.png)
