### ISSUE TITLE
[BUG] Adding whitespace around nbsp

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#61]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version:  0.5.2

## Issue
A `&nbsp;` without whitespace around it shouldnt have whitespace added around it.  This should be applied to any content enclosed within one of the HTML element which doesnt create a block - i.e. `span`, `strong`, `i`, etc.

```diff
-                <th data-field="expired"><i class="fa fa-exclamation-circle">&nbsp;</i></th>
+                        <th data-field="expired">
+                            <i class="fa fa-exclamation-circle">
+                            &nbsp;
+                            </i>
+                        </th>
```

## How To Reproduce
See above

**Comment by christopherpickering** [comment]
In the output webpage, is there an extra space added?
