### ISSUE TITLE
[BUG] [Formatter] Repeated indentation of multiline JS string with --format-js

### ISSUE THREAD

**Issue by vEnhance** [Riverside-Healthcare/djLint#614]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Arch Linux
 - Python Version (``python --version``) = 3.10.10
 - djLint Version (``djlint --version``) = 1.25.0
 - template language: djhtml

## Issue

This was encountered in https://github.com/vEnhance/otis-web/issues/191#issuecomment-1522306604 and I am forwarding upstream at the request of @christopherpickering.

The snippet

```jinja
<script type="text/javascript">
    let s = `
        <p>Text.</p>`;
</script>
```

is not reformatted properly by `djlint` with `--format-js`. Running the command causes the text line to be indented one further level each time.

## How To Reproduce

Run `djlint --format-js --reformat snippet.html` on the snippet above. Example terminal session below as both text and image.

```
I /tm/djlint >> cat snippet.html                                                            dj🐍 [15:25]
<script type="text/javascript">
    let s = `
        <p>Text.</p>`;
</script>
I /tm/djlint >> djlint --version                                                            dj🐍 [15:25]
djlint, version 1.25.0
I /tm/djlint >> python --version                                                            dj🐍 [15:25]
Python 3.10.10
I /tm/djlint >> djlint --reformat --format-js snippet.html                                  dj🐍 [15:26]

Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


tmp/djlint/snippet.html
───────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -1,4 +1,4 @@

 <script type="text/javascript">
     let s = `
-        <p>Text.</p>`;
+            <p>Text.</p>`;
 </script>

1 file was updated.

I /tm/djlint [1] >> djlint --reformat --format-js snippet.html                              dj🐍 [15:28]

Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


tmp/djlint/snippet.html
───────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -1,4 +1,4 @@

 <script type="text/javascript">
     let s = `
-            <p>Text.</p>`;
+                <p>Text.</p>`;
 </script>

1 file was updated.
```

![image](https://user-images.githubusercontent.com/3750940/234417861-21c3fad7-16ea-40c9-a27f-41ab169490d0.png)

**Comment by vEnhance** [comment]
Might be related to #600.

**Comment by christopherpickering** [comment]
Thanks, I looked into it a bit and it seems like the contents of `...` blocks are not touched by jsbeautifier. I'll see what can be done to fix this. Thanks for opening the issue!

**Comment by christopherpickering** [comment]
Sorry for the delay, this should be fixed by the next release.
