### ISSUE TITLE
[FEATURE] Support external non-regex python rules

### ISSUE THREAD

**Issue by Alabate** [Riverside-Healthcare/djLint#618]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request
It's nice that most of the linting rules are 100% regex, but sometimes it's not enough: 

We use Django `ManifestStaticFilesStorage` that generate a manifest file to handle static file urls, and if a file is not in this manifest (eg. wrong path), it will just crash on template rendering. I want to catch that issue before going to production, but it's not possible to do that without parsing the manifest file to get "allowed" file pathes.

I don't think that's this rule should be integrated globally into this project, because it's hard to make it generic (the manifest can move, can be out of date, etc.). However it would be nice to have a way to link a python file in `.djlint_rules.yaml` to make it on our side. Also, with the same method, we could move the code of `H025` into a separate python file.

Are you interested by this feature? I might create a PR for that if yes.

**Comment by christopherpickering** [comment]
That would be pretty cool! I'd be happy with a pr if you have a nice way to make it work. Thanks!
