### ISSUE TITLE
djlint max_line_length still doing wrong line break

### ISSUE THREAD

**Issue by kopax-polyconseil** [Riverside-Healthcare/djLint#622]
Hello here, before all, I'd like to thanks again for providing this awesome plugin for free.

Following the fix you shipped for `max_line_length` in v1.23.0, we still encounter not normal behavior for this settings, as reported by one of my mate here:

https://github.com/pass-culture/pass-culture-main/pull/6406#discussion_r1185756933

- This line is reindented: https://github.com/pass-culture/pass-culture-main/blob/f05573db512706f8bdd37280cc64e9d94cdc47dd/api/src/pcapi/routes/backoffice_v3/templates/offer/list.html#L125-L127
- This line is not reindented: https://github.com/pass-culture/pass-culture-main/blob/f05573db512706f8bdd37280cc64e9d94cdc47dd/api/src/pcapi/routes/backoffice_v3/templates/offer/list.html#L121

Both lines are having the same length `39`, if we add the preceding indent from the same line, they are both length `55`.

[Our configuration](https://github.com/pass-culture/pass-culture-main/blob/master/api/src/pcapi/routes/backoffice_v3/.djlintrc#L8) use `max_line_length` = `140`.

Our djlint version : 1.23.0 (source: [requirements.txt](https://github.com/pass-culture/pass-culture-main/blob/master/api/requirements.txt#L89))

**Comment by christopherpickering** [comment]
This seems to be fixed in v1.23.1 with https://github.com/Riverside-Healthcare/djLint/pull/593

Thanks for reporting!
