### ISSUE TITLE
[FEATURE] [Formatter] Add config option to put tag content in new line if attributes are split over multiple lines

### ISSUE THREAD

**Issue by timoludwig** [Riverside-Healthcare/djLint#624]
## Feature Request

Thanks a lot for this tool! In general, I like the output of the formatter.

However, I would prefer if the content of a tag would be in its separate line when the tag attributes itself are split over multiple lines.
E.g., the following pattern:
```
<a id="link"
   href="{% url "myview" %}"
   class="class another-class and-yet-another-one">linktext</a>
```
I would like to be formatted like this:
```
<a id="link"
   href="{% url "myview" %}"
   class="class another-class and-yet-another-one">
    linktext
</a>
```
And only is placed on the same line when the entire tag fits into one line:
```
<a id="link" href="{% url "myview" %}" class="class another-class">linktext</a>
```

I'm aware that maybe not all users would prefer this formatting, so I suggest to add a config option for this. But I would obviously also be fine if this was the default behavior.

If you agree with the motivation behind this idea, I would be happy to contribute this feature if you could point me in the right direction. I assume that we could modify this function:
https://github.com/Riverside-Healthcare/djLint/blob/fbb2866ce3d84eee9c25c67c3c02a7fc023da052/src/djlint/formatter/condense.py#L135-L147

So it only condenses the line if the beginning of the tag is also included?

**Comment by timoludwig** [comment]
Moreover, I just noticed that in some cases, it was possible to achieve this formatting manually previously, e.g. the block:
```
<a href="{% url "myview" %}"
   class="class another-class and-yet-another-one"
   target="_blank"
   rel="noopener noreferrer">
    linktext
</a>
```
remained unchanged in version `v1.19.7` and earlier, but is reformatted in versions `v1.20.0` and above to:
```
<a href="{% url "myview" %}"
   class="class another-class and-yet-another-one"
   target="_blank"
   rel="noopener noreferrer">linktext</a>
```
Although I do not find a corresponding entry in the changelog.
Is this an unwanted side effect of [this change](https://github.com/Riverside-Healthcare/djLint/compare/v1.19.17...v1.20.0#diff-df92aa5ddb54f17f4d097319a906217979d2746dbb8ec0eb90d88df1f0fc9d8b)?
Then I would actually consider this a bug now :thinking:

**Comment by christopherpickering** [comment]
Hey @timoludwig v20 fixed some inconsitencies in where lines were broken > the math for line lenght was not correctly counting leading spaces in some cases.

The current behavior checks the last line in the tag to see if the tag contens/close bracket should be spread over multiple lines or not.
Since in your case the last line + contents + close bracket are < line lenth, they are kept on a single line.

We could add a config option to basically say if there are any breaks in the tag attributes (class, id, etc), they we can also break the contents. 

This line `len(match.group(1).splitlines()[-1] + match.group(3) + match.group(4)) ` would become `len(match.group(1) + match.group(3) + match.group(4)) ` when the flag is present.

I'd be happy with a pr with a new flag if that floats your boat :)

**Comment by timoludwig** [comment]
> Hey @timoludwig v20 fixed some inconsitencies in where lines were broken > the math for line lenght was not correctly counting leading spaces in some cases.

Ah okay, I thought [`v1.19.7`](https://github.com/Riverside-Healthcare/djLint/releases/tag/v1.19.17) introduced the fixes for the max length? That's why I wondered about the changed behavior in [`v1.20.0`](https://github.com/Riverside-Healthcare/djLint/releases/tag/v1.20.0) which only mentions changes to the yaml format...

To reproduce this, I created a file:

`cat test.html`
```
<a href="{% url "myview" %}"
   class="class another-class and-yet-another-one"
   target="_blank"
   rel="noopener noreferrer">
    linktext
</a>
```

Then I ran djlint version `v1.19.7` against it, which did not change anything:

`djlint --version`
```
djlint, version 1.19.7
```

`djlint --reformat test.html`
```
Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00


0 files were updated.
```

But when running djlint version `v1.20.0`, it reformats the file:

`djlint --version`
```
djlint, version 1.20.0
```

`djlint --reformat test.html`
```
Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00


test.html
────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -1,6 +1,4 @@

 <a href="{% url "myview" %}"
    class="class another-class and-yet-another-one"
    target="_blank"
-   rel="noopener noreferrer">
-    linktext
-</a>
+   rel="noopener noreferrer">linktext</a>

1 file was updated.
```

So there seems to be something else going on, apart from the documented bug fixes.

> We could add a config option to basically say if there are any breaks in the tag attributes (class, id, etc), they we can also break the contents.
> 
> This line `len(match.group(1).splitlines()[-1] + match.group(3) + match.group(4)) ` would become `len(match.group(1) + match.group(3) + match.group(4)) ` when the flag is present.
> 
> I'd be happy with a pr with a new flag if that floats your boat :)

Ok, sounds very good! :+1:
This would also make it unnecessary to dig deeper into the problem described above.
I will give it a shot!

**Comment by christopherpickering** [comment]
maybe you are right, I loose track of v #'s :D I'm not very good about keeping the commit notes fully covering changes 🙈

**Comment by christopherpickering** [comment]
I found the fix you were looking for I think.. https://github.com/Riverside-Healthcare/djLint/pull/593 in v 1.23.1

**Comment by timoludwig** [comment]
> I found the fix you were looking for I think.. #593 in v 1.23.1

Ah okay I get it, thanks for having a look! Then this issue is in fact a feature request and not a bug :wink:
