### ISSUE TITLE
[BUG] trans[late] value containing HTML modified by reformatter

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#63]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version:  0.5.2

## Issue

HTML tags inside the `{% trans %}` cause the value to be reformatted, which means any existing translations will be detached from the string (unless django's fuzzy translation logic magically re-aligns them).

This is a bit like #26.

```diff
-                <p>{% trans 'Please do <b>Blah</b>.' %}</p>
+                            <p>
+                                {% trans 'Please do
+                                <b>
+                                Blah
+                                </b>
+                                .' %}
+                            </p>
```

## How To Reproduce
See above.

**Comment by christopherpickering** [comment]
Thanks, adding ``| {\%[ ]trans[ ][^}]*?\%}`` to the ignored block pattern seems to resolve this one.
