### ISSUE TITLE
[FEATURE] Report redundant HTML

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#64]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

A bit simpler than #58, there are lots of redundant HTML syntax which can be removed.  e.g. empty `style`, `script`, and IMO any other empty non-auto-closing element unless it has an id/class/etc.

```diff
-
-    <style>
-
-    </style>
+    <style></style>
```

**Comment by christopherpickering** [comment]
Nice, yep, I think we can catch that with some simple regex: ``<(\w+)\s*?>\s*?<\/\1>``

I'll add a rule in.
