### ISSUE TITLE
[BUG] [Formatter] Edge case where closing tag not aligned with opening tag

### ISSUE THREAD

**Issue by timoludwig** [Riverside-Healthcare/djLint#640]
## System Info
 - OS: Arch Linux
 - Python Version: 3.11.3
 - djLint Version: `v1.20.0` and above
 - template language: Django

## Issue

There seems to be a weird edge case where the closing tag is not aligned with the opening tag.

## How To Reproduce

In versions `v1.19.7` and below, the following fragment was formatted correctly:
```
<h1>
    {% if condition1 %}<span class="cls"></span>{% endif %}
    {% if condition2 %}"{{ text }}"{% endif %}
</h1>
```

In versions `v1.20.0` and above (up until the current version `v1.27.0`), it is formatted like this:
```
<h1>
    {% if condition1 %}<span class="cls"></span>{% endif %}
    {% if condition2 %}"{{ text }}"{% endif %}
    </h1>
```

**Comment by christopherpickering** [comment]
Odd stuff, its something w/the quotes in the second if statement. I'll check that out!
