### ISSUE TITLE
[BUG] [Formatter] Block assignments in Nunjucks don't have proper indentation

### ISSUE THREAD

**Issue by joshjavier** [Riverside-Healthcare/djLint#646]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: EndeavourOS (Kernel: 6.3.1-arch2-1)
 - Python Version: 3.11.3
 - djLint Version: 1.27.2 (npm install)
 - template language: Nunjucks

## Issue
When using the `set` tag in [block assignment syntax](https://mozilla.github.io/nunjucks/templating.html#set), the lines are not indented properly.

## How To Reproduce
Given the input:

```nunjucks
{% if tag %}
  {% set cta %}{% include "partials/cta.njk" %}{% endset %}
{% endif %}

{% if tag %}
  {% set cta %}
    {% include "partials/cta.njk" %}
  {% endset %}
{% endif %}
```

I get the output:

```nunjucks
{% if tag %}
  {% set cta %}
  {% include "partials/cta.njk" %}
{% endset %}
{% endif %}

{% if tag %}
  {% set cta %}
  {% include "partials/cta.njk" %}
{% endset %}
{% endif %}
```

For reference, here are the contents of my `.djlintrc`:

```json
{
  "preserve_blank_lines": "true",
  "ignore": "T003,H006",
  "max_line_length": "100"
}
```

**Comment by christopherpickering** [comment]
thanks for this one - there is a big challeng here as set can be used as a single statement, or as a block.

Some logic needs to be added to check is a "open" block has an "endblock" before the next occourance of the "open".
If there is a "endblock" then indent can be added.

As a workaround (if you aren't using set both ways) you can add `--custom-blocks "set"` to fix the indent.
