### ISSUE TITLE
[BUG] %if within HTML attribute

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#66]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version:  0.5.2

## Issue
Lines are merged if an `{% if %}` is used to populate the value of a HTML attribute
e.g.

```diff
-<span
-    title="
-    {% if eev.status == eev.STATUS_CURRENT %}
-        {% trans 'A' %}
-    {% elif eev.status == eev.STATUS_APPROVED %}
-        {% trans 'B' %}
-    {% elif eev.status == eev.STATUS_EXPIRED %}
-        {% trans 'C' %}
-    {% endif %}
-    ">
+<span title=" {% if eev.status == eev.STATUS_CURRENT %} {% trans 'A' %} {% elif eev.status == eev.STATUS_APPROVED %} {% trans 'B' %} {% elif eev.status == eev.STATUS_EXPIRED %} {% trans 'C' %} {% endif %} ">
```

**Comment by christopherpickering** [comment]
Thanks, is this an issue?
The formatter first puts all the attribs back on one line, and then splits them back out, but template syntax is kept on one line.

**Comment by jayvdb** [comment]
I have a few of these, and the reformatted lines are 1000+ cpl because of long strings and many branches.  I couldnt get this change through code review as it reduces readability considerably.

**Comment by christopherpickering** [comment]
If the length of the if statement is over our threshold for readable lines, we should probably format it then. I'll check that out.

**Comment by jayvdb** [comment]
I can rewrite the source, using a variable to store the `title`.  IIRC, there were only three of these, so I will take that approach if this isnt easy to fix.

**Comment by christopherpickering** [comment]
I think I should fix it :). We use that syntax all the time as well.

**Comment by christopherpickering** [comment]
I think I've got something working. I'll put a release out in a bit for you to test.

this:
```html
<span {%if a%}required{%endif%}title="{% if eev.status == eev.STATUS_CURRENT %} {% trans 'A' %} {% elif eev.status == eev.STATUS_APPROVED %} {% trans 'B' %} {% elif eev.status == eev.STATUS_EXPIRED %} {% trans 'C' %}{% endif %}" class="asdf {%if a%}b{%endif%} asdf" {%if a%}checked{%endif%}>
```

becomes this:
```html
-<span {%if a%}required{%endif%}title="{% if eev.status == eev.STATUS_CURRENT %} {% trans 'A' %} {% elif eev.status == eev.STATUS_APPROVED %} {% trans 'B' %} {% elif eev.status == eev.STATUS_EXPIRED %} {% trans 'C' %}{% endif %}" class="asdf {%if a%}b{%endif%} asdf" {%if a%}checked{%endif%}>
+<span {% if a %}
+          required
+      {% endif %}
+      title="{% if eev.status == eev.STATUS_CURRENT %}
+                 {% trans 'A' %}
+             {% elif eev.status == eev.STATUS_APPROVED %}
+                 {% trans 'B' %}
+             {% elif eev.status == eev.STATUS_EXPIRED %}
+                 {% trans 'C' %}
+             {% endif %}"
+      class="asdf 
+             {% if a %}
+                 b
+             {% endif %}
+             asdf"
+      {% if a %}
+          checked
+      {% endif %}>
```
