### ISSUE TITLE
Preserve one line

### ISSUE THREAD

**Issue by ebiscaia** [Riverside-Healthcare/djLint#675]
Hi guys,

I think this option makes more sense than a simple preserve-lines because sometimes you would like a gap to make the code more readable, but not having it as disjoined parts.

Best regards,

Eduardo

**Comment by christopherpickering** [comment]
Hey thanks. Can you give an example of how it would be used? I'm not following you completely.

**Comment by ebiscaia** [comment]
Sorry, what I mean is to remove all the blank lines but one when there are two or more consecutive blank lines. Today the formatter either removes all the lines (no option provided) or keep them all (--preserve-blank-lines). I have the following snippet:

```
<button class="navbar-toggler"                                                                                                                                                                                        
   Code here                                                                                                                                                                          
</button>


                                                                                                                                                                                                            
<div class="collapse navbar-collapse" id="navbarToggle">
    Code here                                                                                                                                                           
</div>
```

I would like after formatting is:```
<button class="navbar-toggler"                                                                                                                                                                                        
   Code here                                                                                                                                                                          
</button>
                                                                                                                                                                                                       
<div class="collapse navbar-collapse" id="navbarToggle">
    Code here                                                                                                                                                           
</div>
```

Thanks again

**Comment by christopherpickering** [comment]
Ok cool, so basically we would consolidate blank lines into a max #?
Add a --max-blank-lines=# arg or something along these lines?

**Comment by ebiscaia** [comment]
Yep, that is what I was thinking.

**Comment by christopherpickering** [comment]
hey @ebiscaia, thanks! The next release will include a `--max-blank-lines <integer>` flag that will let you consolidate blank lines down to a fixed number. You can also set it through the json or toml files.
