### ISSUE TITLE
[BUG] [Formatter] `line_break_after_multiline_tag` not always breaking as expected

### ISSUE THREAD

**Issue by malo-cayocca** [Riverside-Healthcare/djLint#680]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
- OS: ubuntu 20.04
- Python Version 3.8.10
- djLint Version 1.30.0
- template language: django templates

## Issue
Hi ! I'm trying the new `line_break_after_multiline_tag=true` option, which is pretty nice. 

I have run into a difference in behaviour depending on tags, and was wondering if all could behave alike (like the `div` in the following example). I have noticed this mostly on `<a>` tags.

## How To Reproduce
Here is the initial situation, I would expect it to remain identical after reformatting
```
<div class="ds-flex ds-items-center ds-justify-center"
     style="grid-column: 3/4">
    {{ here_is_a_long_variable }}
</div>
<span class="ds-flex ds-items-center ds-justify-center"
      style="grid-column: 3/4">
    {{ here_is_a_long_variable }}
</span>
```
After reformating, the `span` gets condensed on one line, whereas the `div` does not : 
```
<div class="ds-flex ds-items-center ds-justify-center"
     style="grid-column: 3/4">
    {{ here_is_a_long_variable }}
</div>
<span class="ds-flex ds-items-center ds-justify-center"
      style="grid-column: 3/4">{{ here_is_a_long_variable }}</span>
```

**Comment by christopherpickering** [comment]
Thanks :) What is your config? With the default options it seems to work as expected.

**Comment by malo-cayocca** [comment]
Here is my current config :
```
[tool.djlint]
require_pragma = true
profile = "django"
custom_blocks = "stage, cache, flatblock, section, csp_compress"
ignore_blocks = "set_global_context"
custom_html = "..."
blank_line_after_tag = "extends, endblock"
max_line_length = 120
line_break_after_multiline_tag = true
ignore = "H021,H023,H030,H031"
```

I've just tested again and `span` might not be the correct example (although I'm pretty sure it did not work an hour ago ...), with an `a` tag however I am able to reproduce :

```
<a class="ds-flex ds-items-center ds-justify-center"
   style="grid-column: 3/4">
    {{ here_is_a_long_variable }}
</a>
```
becomes
```
<a class="ds-flex ds-items-center ds-justify-center"
   style="grid-column: 3/4">{{ here_is_a_long_variable }}</a>
```

**Comment by christopherpickering** [comment]
Thanks, I see what is going on now. I updated the online demo so we can run there:

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/7fb597a4-c8b8-4de5-8071-816331ff7f8c)

In the code, we are still condensing if the sum of the parts is less than your max line length.
![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/661e3538-38ba-4274-80e5-dfa8afdf1822)


It is a bit confusing and not exactly following the name of the flag.

We should probably update it so that if there is a break inside the tag then we ALWAYS break the tag contents as you were execting.
