### ISSUE TITLE
[BUG] [Formatter] Formating of {% set = .. %} generate unparsable result for Jina2

### ISSUE THREAD

**Issue by ikus060** [Riverside-Healthcare/djLint#682]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Debian Bullseye
 - Python Version: 3.10
 - djLint Version: 1.30 (issue since 1.25.1)
 - template language: Jinja2

## Issue
Formating 
```
{% set classes =  {
'sPaging': 'd-flex justify-content-center ',
'sPageButton': 'btn btn-outline-primary ms-1 me-1',
'sPageButtonActive': 'active',
}%}
```
Output
```
{% set classes = {
  sPaging: "d-flex justify-content-center ",
  sPageButton: "btn btn-outline-primary ms-1 me-1",
  sPageButtonActive: "active"
} %}
```

The indentation is fixed, but the quotes around `sPaging` are required for Jinja2.

This changes seams to be introduce by https://github.com/Riverside-Healthcare/djLint/commit/85aca4cf5dc368111e4e459d38c99beaae6fa3a5

I don't see an option to disable that behavior either.

**Comment by christopherpickering** [comment]
Thanks, I will make quoted keys the default if Jinja requires it. This option was for jinja/njk so we will follow their lead :)

**Comment by christopherpickering** [comment]
I also added flags to disable set/function formatting in case other issues come up and I cannot resolve quickly.
