### ISSUE TITLE
[BUG] [Formatter] incorrect formatting of {% form tags

### ISSUE THREAD

**Issue by krims0n32** [Riverside-Healthcare/djLint#708]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: archlinux
 - Python Version: 3.11.3
 - djLint Version: v2023.7.3 (vscode)
 - template language: django-html

## Issue
Django template tag that starts with "for" is rendered indented. djlint thinks it's the start of a for loop.

## How To Reproduce

Type:

`{% form ... %}`

in a template and you will see that djlint indents everything below as in an unclosed for loop. Should probably check for the whole word "for" instead of beginning with "for".

**Comment by christopherpickering** [comment]
Hey @krims0n32 this was fixed in a previous release, you most likely need to update your djlint install (updating vscode djlint will not update djlint, it is separate code.)
