### ISSUE TITLE
[FEATURE] Documentation formatting seems to go wrong

### ISSUE THREAD

**Issue by KommuSoft** [Riverside-Healthcare/djLint#713]
- [X] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [X] I've read the [docs](https://djlint.com)

## Feature Request: improve the documentation render engine

The documentation file has hyphens for the template tags, indeed: https://github.com/Riverside-Healthcare/djLint/blob/07dfbad680856845f0d4ecbf399e40f230d16c80/docs/src/docs/best-practices.md?plain=1#L15-L22

it here likely writes `{% if condition -%}` to prevent the render engine from interpreting the `{% if condition %}` itself, but likely the render engine should remove the hyphens in the documentation online: https://djlint.com/docs/best-practices/

**Comment by christopherpickering** [comment]
Thanks yeah it looks like the markdown parser or something is removing the spaces. I'll reopen to check that.
The dashes in there are for jinja and nunjucks.
