### ISSUE TITLE
[FEATURE] [Formatter] sorl-thumbnail's django template tag indentation

### ISSUE THREAD

**Issue by josvleeuwen** [Riverside-Healthcare/djLint#714]
## System Info
 - OS: ubuntu 23.04
 - Python Version 3.11.1
 - djLint Version 1.31.1
 - template language: django + sorl-thumbnail

## Issue
When I use sorl-thumbnail to generate a thumbnail of an image with this code the formatter messes up the indentation:

```
    // <-- 4 spaces
    {% thumbnail person.profile_photo "200x200" crop="center" as im %}
    <img src="{{ im.url }}"
         width="{{ im.width }}"
         height="{{ im.height }}"
         class="img-thumbnail"
         alt="{{ person.name }}">
{% endthumbnail %}
// <-- 0 spaces
```

## How To Reproduce
Copy & paste the code above.

**Comment by christopherpickering** [comment]
Hey, can you add your config? Did you add thumbnail as a custom block in it?

**Comment by christopherpickering** [comment]
@josvleeuwen I will add support for this in the next release. Thanks!
