### ISSUE TITLE
[BUG] [Formatter] Formatting for contents of {% set %} tags

### ISSUE THREAD

**Issue by Yuyuutsu** [Riverside-Healthcare/djLint#725]
- [X] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [X] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [X] I've read the [docs](https://djlint.com)

## System Info
 - OS: e.g. MacOS Ventura 13.4
 - Python Version (``3.10.8``)
 - djLint Version ([v1.19.2](https://github.com/Riverside-Healthcare/djLint/releases/tag/v1.19.2))
 - template language: Jinja

## Issue
Raising the issue of the formatters short comings with formatting json inside and element as [spoken on discord](https://discord.com/channels/885044106391343115/885044106856902708/1033016734757695618). 
When running formatter it flattens the json elements when inside an element.

## How To Reproduce

1. Run `djlint . --check` with a file that has json element inside an element
2. It should output in the terminal a flattened formatting:
```
 {% set breadcrumbs = {
-  "ariaLabel": 'Back',
-  "itemsList": [
-    {
-      "url": url_for("post_submission.get_thank_you"),
-      "id": "top-previous",
-      "text": _("Back"),
-      "attributes": {
-        "data-ga": 'click',
-        "data-ga-category": 'Navigation',
-        "data-ga-action": 'Previous link click'
-      }
-    }
-  ]
+"ariaLabel": 'Back',
+"itemsList": [
+{
+"url": url_for("post_submission.get_thank_you"),
+"id": "top-previous",
+"text": _("Back"),
+"attributes": {
+"data-ga": 'click',
+"data-ga-category": 'Navigation',
+"data-ga-action": 'Previous link click'
+}
+}
+]
 } %} 

```

**Comment by christopherpickering** [comment]
Fyi, djlint is on v1.32 now and this has been mostly corrected.

Souce code:
```html
{% set breadcrumbs = {
  "ariaLabel": 'Back',
  "itemsList": [
    {
      "url": url_for("post_submission.get_thank_you"),
      "id": "top-previous",
      "text": _("Back"),
      "attributes": {
        "data-ga": 'click',
        "data-ga-category": 'Navigation',
        "data-ga-action": 'Previous link click'
      }
    }
  ]
  }
%} 
```

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/a814177b-1f5d-43f3-9ee8-3429e7c0ed30)

Are there other issues in the latest release?
