### ISSUE TITLE
[BUG] [Formatter]It will parse the HTML tags in the string.

### ISSUE THREAD

**Issue by Taikono-Himazin** [Riverside-Healthcare/djLint#742]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 10
 - Python Version (3.11.4)
 - djLint Version (1.32.1)
 - template language: django templete

## Issue
It will parse the HTML tags in the string.

## How To Reproduce
Using djlint for HTML with below code.
```
{{ some_val | default:'some_comment1<br>some_comment2' }}
```
becomes as follows
Doing this will prevent `{{}}` from being treated as a variable and will break the display.
```
{{ some_val | default:'some_comment1
<br>
some_comment2' }}
```
I would expect something like
```
{{ some_val | default:'some_comment1<br>some_comment2' }}
```

**Comment by christopherpickering** [comment]
Thanks for reporting.
