### ISSUE TITLE
Allow to stop adding blank line for indent block.

### ISSUE THREAD

**Issue by pinkfrog9** [Riverside-Healthcare/djLint#746]
Given the follow code,
<img width="188" alt="image" src="https://github.com/Riverside-Healthcare/djLint/assets/107285219/12ac8147-b562-49b5-bdab-30b5157f20df">

Since the second block is indented, there is no need to add a blank line before it even if the "add blank line for tag" is enabled for "block" tag.
<img width="214" alt="image" src="https://github.com/Riverside-Healthcare/djLint/assets/107285219/5e40084f-045c-4e7e-8fe6-5ba950448f67">

I cannot simply remove "block" from the "add blank line for tag" list. Since the following case is desired.
<img width="182" alt="image" src="https://github.com/Riverside-Healthcare/djLint/assets/107285219/bd484b90-2605-42be-b12d-9c2fb42c2c99">

**Comment by christopherpickering** [comment]
Hey man, I can't reproduce this. Please follow the template and include your config.
