### ISSUE TITLE
[BUG] [Formatter] object variable gets turned into repr of object type

### ISSUE THREAD

**Issue by rafales** [Riverside-Healthcare/djLint#756]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - MacOS 13.5.2 (22G91)
 - Python Version: Python 3.11.4
 - djLint Version: 1.32.1
 - template language: e.g. jinja

## Issue
Well, I use variable "object" in my templates, similar to what django does (`{% for object in object_list %}`).

The following:
```
{{ do_something(object) }}
```
Gets turned into:
```
{{ do_something(<class 'object'>) }}
```

<img width="362" alt="image" src="https://github.com/Riverside-Healthcare/djLint/assets/919812/6c51f099-38b8-46ee-96c9-26fe1cf163ce">

## How To Reproduce
1. Use above snippet as template example.
2. Run `djlint --reformat example.html`.

## Additional info

Config used (`pyproject.toml`):
```
[tool.djlint]
profile = "jinja"
indent = 2
ignore = "H021,H006,H013"
```

**Comment by rafales** [comment]
🎉 🔥 Thank you!

**Comment by rob101** [comment]
This issue still persist if you use the object inside a tag, e.g. `{% set my_var = object %}`. See https://github.com/Riverside-Healthcare/djLint/issues/756
